from app.services.probabilistic_record_linkage import CONTRACT_VERSION, reference_probabilistic_record_linkage_bundle
b=reference_probabilistic_record_linkage_bundle()
print("PASS - Platform Core v3.79.0 Probabilistic Record Linkage & Entity Matching Objects")
print(f"CONTRACT={CONTRACT_VERSION}")
print(f"FEATURE_DEFINITIONS={len(b.feature_definitions)}")
print(f"BLOCKING_RULES={len(b.blocking_rules)}")
print(f"CANDIDATE_PAIRS={len(b.candidate_pairs)}")
print(f"FEATURE_OBSERVATIONS={len(b.feature_observations)}")
print(f"MATCH_PROBABILITY={b.probability_records[0].match_probability}")
print(f"REVIEWS={len(b.reviews)}")
print(f"DECISION_STATE={b.decisions[0].decision_state.value}")
print("MATCH_PROBABILITY_IS_IDENTITY_FACT=false")
print("LINKAGE_OUTPUT_IS_IDENTITY_EVIDENCE=false")
print("AUTO_MERGE_ALLOWED=false")
print("IDENTITY_GRAPH_MUTATION_PERFORMED=false")
