from fastapi import APIRouter, Depends, Request
from urllib.parse import urlsplit
from sqlalchemy import func, select, text
from sqlalchemy.orm import Session

from ..dependencies import get_session, require_read
from ..models import (
    CalculationTrace,
    ClaimRecord,
    Entity,
    EntityAlias,
    EvidenceFoundation,
    EvidenceRecord,
    EvidenceReview,
    EvidenceReviewAssignment,
    EvaluationCheckResult,
    EvaluationDefinition,
    EvaluationRun,
    ImportJob,
    KnownLimitation,
    LedgerEntry,
    LiveDataConnector,
    LiveDataIngestionRun,
    LiveDataObservation,
    InternationalLawRecord,
    ScientificDataRecord,
    EconomicDataRecord,
    GeospatialFeature,
    TimeSeriesDefinition,
    TimeSeriesPoint,
    ScientificDataAsset,
    ScientificStorageBackend,
    ScientificStoredObject,
    ScientificProcessingAdapter,
    ScientificProcessingRun,
    ResearchProjectRecord,
    ResearchModelRecord,
    ResearchModelVersionRecord,
    ResearchVariableRecord,
    ResearchParameterRecord,
    ResearchScenarioRecord,
    ResearchModelRunRecord,
    ResearchResultRecord,
    VisualReasoningObjectRecord,
    VisualReasoningElementRecord,
    VisualReasoningRelationRecord,
    VisualReasoningLayerRecord,
    VisualReasoningAnnotationRecord,
    VisualReasoningSnapshotRecord,
    CrossProductVisualResearchObjectRecord,
    CrossProductVisualResearchMemberRecord,
    CrossProductVisualResearchRelationRecord,
    CrossProductVisualResearchViewRecord,
    CrossProductVisualResearchSnapshotRecord,
    ReproducibleVisualKnowledgePackageRecord,
    ReproducibleVisualKnowledgeInputRecord,
    ReproducibleVisualKnowledgeEnvironmentRecord,
    ReproducibleVisualKnowledgeReplayPlanRecord,
    ReproducibleVisualKnowledgeVerificationRecord,
    ReproducibleVisualKnowledgeSnapshotRecord,
    ForensicInvestigationRecord, ForensicObjectRecord, ForensicEvidenceItemRecord, ForensicEvidenceSourceBindingRecord,
    ForensicProvenanceActivityRecord, ForensicObjectRelationRecord, ForensicSnapshotRecord,
    ForensicClaimRecord, ForensicClaimEvidenceAssessmentRecord, ForensicContradictionRecord, ForensicHypothesisRecord,
    ForensicHypothesisEvidenceAssessmentRecord, ForensicHypothesisRelationRecord, ForensicReasoningSnapshotRecord,
    ForensicEventRecord, ForensicEventEvidenceBindingRecord, ForensicEventParticipantRecord, ForensicEventRelationRecord,
    ForensicEventReconstructionRecord, ForensicTimelineViewRecord, ForensicTimelineSnapshotRecord,
    ForensicMediaArtifactRecord, ForensicMediaDerivativeRecord, ForensicMediaMetadataRecord, ForensicMediaFingerprintRecord,
    ForensicMediaSegmentRecord, ForensicMediaComparisonRecord, ForensicMediaProvenanceSnapshotRecord,
    VisualizationSpecificationRecord,
    RendererDefinitionRecord,
    RendererVersionRecord,
    RendererCompatibilityRuleRecord,
    RendererResolutionRecord,
    SystemMapRecord,
    SystemMapBoundaryRecord,
    SystemMapDomainRecord,
    SystemMapMembershipRecord,
    SystemMapViewRecord,
    FlowMapRecord,
    FlowMapChannelRecord,
    FlowMapFlowRecord,
    FlowMapNodeStateRecord,
    FlowMapViewRecord,
    ScenarioLandscapeRecord,
    ScenarioLandscapeScenarioRecord,
    ScenarioLandscapeDimensionRecord,
    ScenarioLandscapeValueRecord,
    ScenarioLandscapeViewRecord,
    ModelCanvasRecord,
    ModelCanvasNodeRecord,
    ModelCanvasEdgeRecord,
    ModelCanvasControlRecord,
    ModelCanvasStateRecord,
    ModelCanvasViewRecord,
    ScenarioComputePlanRecord,
    ScenarioComputeCaseRecord,
    ScenarioComputeRequestRecord,
    ScenarioComputeAttemptRecord,
    ScenarioComputeResultBindingRecord,
    UncertaintyDefinitionRecord,
    SensitivityStudyRecord,
    SensitivityFactorRecord,
    SensitivityMeasureRecord,
    EnsembleRecord,
    EnsembleMemberRecord,
    EnsembleStatisticRecord,
    UncertaintyComputeRunRecord,
    CausalGraphRecord, CausalVariableRecord, CausalEdgeRecord, CausalInterventionRecord, CausalIdentificationRecord, CausalEstimateRecord, CausalDiagnosticRecord,
    MapLayer,
    StacCollection,
    StacItem,
    LiveDataSource,
    OperationalFacility,
    FacilityObservation,
    HumanitarianCondition,
    PredicateDefinition,
    ProvenanceActivity,
    ProvenanceLink,
    Relationship,
    RelationshipReview,
    SourceSnapshot,
    TrustAttestation,
    TrustFinding,
    TrustIncident,
    ValidationEvent,
)
from ..schemas import MetaResponse, RegistryStats

router = APIRouter(tags=["Service"])


@router.get("/health")
def health(request: Request):
    return {
        "ok": True,
        "service": request.app.state.settings.app_name,
        "version": request.app.state.settings.version,
        "environment": request.app.state.settings.environment,
        "knowledge_graph": True,
        "evidence_ledger": True,
        "provenance_records": True,
        "unified_public_api": request.app.state.settings.public_api_enabled,
        "unified_service_gateway": request.app.state.gateway_settings.enabled,
        "developer_portal": request.app.state.settings.developer_portal_enabled,
        "workflow_engine": request.app.state.settings.workflow_engine_enabled,
        "dossier_center": request.app.state.settings.dossier_center_enabled,
        "trust_center": request.app.state.settings.trust_center_enabled,
        "live_data_gateway": request.app.state.settings.live_data_enabled,
        "international_law_un_connector_pack": True,
        "scientific_data_connector_pack": True,
        "economics_official_statistics_connector_pack": True,
        "geospatial_time_series_scientific_data_fabric": request.app.state.settings.data_fabric_enabled,
        "stac_catalog": request.app.state.settings.data_fabric_enabled,
        "data_fabric_auto_materialize": request.app.state.settings.data_fabric_auto_materialize,
        "strict_free_sources": request.app.state.settings.live_data_strict_free_sources,
        "operational_evidence_facility_registry": True,
        "humanitarian_access_essential_services_fabric": request.app.state.settings.humanitarian_fabric_enabled,
        "country_evidence_federation_reconciliation": request.app.state.settings.country_evidence_federation_enabled,
        "earth_ocean_space_scientific_service_fabric": request.app.state.settings.scientific_service_fabric_enabled,
        "cross_product_evidence_exchange": request.app.state.settings.cross_product_exchange_enabled,
        "distributed_processing_storage_scale": request.app.state.settings.scale_control_plane_enabled,
        "governance_access_audit_control_plane": request.app.state.settings.governance_control_plane_enabled,
        "production_certification_migration_recovery": request.app.state.settings.production_certification_enabled,
        "observability_slo_production_operations": request.app.state.settings.observability_control_plane_enabled,
        "incident_response_change_control_rollback": request.app.state.settings.incident_change_control_enabled,
        "continuity_backup_verification_disaster_recovery": request.app.state.settings.continuity_disaster_recovery_enabled,
        "multi_region_resilience_failover_coordination": request.app.state.settings.multi_region_resilience_enabled,
        "data_lifecycle_archival_integrity_preservation": request.app.state.settings.data_lifecycle_preservation_enabled,
        "federated_core_trusted_node_exchange": request.app.state.settings.federation_trusted_node_exchange_enabled,
        "capacity_forecasting_resource_governance": request.app.state.settings.capacity_resource_governance_enabled,
        "identity_credential_key_lifecycle": request.app.state.settings.credential_key_lifecycle_enabled,
        "scientific_object_storage_processing_adapter_fabric": request.app.state.settings.scientific_object_storage_enabled,
        "research_object_model_foundation": request.app.state.settings.research_object_model_enabled,
        "visual_reasoning_object_model": request.app.state.settings.visual_reasoning_object_model_enabled,
        "visualization_specification_renderer_registry": request.app.state.settings.visualization_renderer_registry_enabled,
        "system_maps": request.app.state.settings.system_maps_enabled,
        "flow_maps": request.app.state.settings.flow_maps_enabled,
        "scenario_landscapes": request.app.state.settings.scenario_landscapes_enabled,
        "interactive_model_canvas": request.app.state.settings.interactive_model_canvas_enabled,
        "scenario_compute_engine": request.app.state.settings.scenario_compute_engine_enabled,
        "uncertainty_sensitivity_ensemble_reasoning": request.app.state.settings.uncertainty_reasoning_enabled,
        "uncertainty_compute_runtime_integration": request.app.state.settings.uncertainty_compute_runtime_enabled,
        "causal_systems_explorer": request.app.state.settings.causal_systems_explorer_enabled,
        "spatial_temporal_visual_reasoning": request.app.state.settings.spatial_temporal_visual_reasoning_enabled,
        "research_librarian_visual_explanation": request.app.state.settings.research_librarian_visual_explanation_enabled,
        "cross_product_visual_research_objects": request.app.state.settings.cross_product_visual_research_enabled,
        "reproducible_visual_knowledge_layer": request.app.state.settings.reproducible_visual_knowledge_enabled,
        "visual_reasoning_runtime_scene_graph": request.app.state.settings.visual_reasoning_runtime_enabled,
        "open_forensics": request.app.state.settings.open_forensics_enabled,
        "forensic_timeline_event_reconstruction": request.app.state.settings.open_forensics_enabled,
        "forensic_spatial_temporal_evidence_integration": request.app.state.settings.open_forensics_enabled,
        "forensic_media_artifact_derivative_provenance": request.app.state.settings.open_forensics_enabled,
        "forensic_quantitative_reconstruction_reproduction_handoffs": request.app.state.settings.open_forensics_enabled,
        "forensic_testimony_statements_documentary_evidence": request.app.state.settings.open_forensics_enabled,
        "forensic_research_graph": request.app.state.settings.open_forensics_enabled,
        "reproducible_investigation_packages": request.app.state.settings.open_forensics_enabled,
        "predictive_model_object_model_forecast_provenance": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_time_series_forecasting_backtesting": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_probabilistic_forecasting_calibration": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_ensembles_model_comparison": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_anomaly_change_point_early_warning": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_spatial_temporal_intelligence": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_causal_predictive_integration": request.app.state.settings.predictive_intelligence_enabled,
        "predictive_decision_intelligence": request.app.state.settings.predictive_intelligence_enabled,
        "reproducible_predictive_intelligence_packages": request.app.state.settings.predictive_intelligence_enabled,
    }


@router.get("/ready")
async def ready(request: Request, db: Session = Depends(get_session)):
    """Deployment readiness.

    `/health` is intentionally a liveness endpoint.  `/ready` is stricter: a
    first-party product service marked REQUIRED must be configured, enabled, and
    operational before Core reports release readiness. Optional integrations are
    visible but do not block Core from serving its own registry/evidence/data
    fabric capabilities.
    """
    db.execute(text("SELECT 1"))
    gateway = await request.app.state.gateway_runtime.health_snapshot()
    settings = request.app.state.settings
    configuration_blockers: list[str] = []
    if settings.public_base_url_required:
        parsed = urlsplit(settings.public_base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            configuration_blockers.append("public_base_url")
    if (
        settings.required_cors_origin
        and settings.required_cors_origin not in settings.cors_origins
    ):
        configuration_blockers.append("required_cors_origin")
    release_ready = bool(gateway["release_ready"] and not configuration_blockers)
    gateway_state = (
        "disabled"
        if gateway["gateway"] == "disabled"
        else ("ready" if gateway["release_ready"] else "blocked")
    )
    return {
        "ok": release_ready,
        "core_version": settings.version,
        "public_base_url_configured": bool(settings.public_base_url),
        "public_base_url_required": settings.public_base_url_required,
        "required_cors_origin_configured": (
            not settings.required_cors_origin
            or settings.required_cors_origin in settings.cors_origins
        ),
        "configuration_blockers": configuration_blockers,
        "database": "ready",
        "knowledge_graph": "ready",
        "evidence_ledger": "ready",
        "unified_public_api": "ready" if settings.public_api_enabled else "disabled",
        "unified_service_gateway": gateway_state,
        "gateway_overall_status": gateway["overall_status"],
        "required_service_count": gateway["required_service_count"],
        "required_ready_count": gateway["required_ready_count"],
        "required_blockers": gateway["required_blockers"],
        "configured_service_count": gateway["configured_service_count"],
        "trust_center": "ready" if settings.trust_center_enabled else "disabled",
        "live_data_gateway": "ready" if settings.live_data_enabled else "disabled",
        "international_law_un_connector_pack": "ready",
        "scientific_data_connector_pack": "ready",
        "economics_official_statistics_connector_pack": "ready",
        "geospatial_time_series_scientific_data_fabric": (
            "ready" if settings.data_fabric_enabled else "disabled"
        ),
        "stac_catalog": "ready" if settings.data_fabric_enabled else "disabled",
        "streaming_alerts_source_reliability": "ready" if settings.streaming_enabled else "disabled",
        "connector_worker": "ready" if settings.reliability_worker_enabled else "disabled",
        "provider_failover": "ready" if settings.provider_failover_enabled else "disabled",
        "operational_evidence_facility_registry": "ready",
        "humanitarian_access_essential_services_fabric": "ready" if settings.humanitarian_fabric_enabled else "disabled",
        "country_evidence_federation_reconciliation": "ready" if settings.country_evidence_federation_enabled else "disabled",
        "earth_ocean_space_scientific_service_fabric": "ready" if settings.scientific_service_fabric_enabled else "disabled",
        "cross_product_evidence_exchange": "ready" if settings.cross_product_exchange_enabled else "disabled",
        "distributed_processing_storage_scale": "ready" if settings.scale_control_plane_enabled else "disabled",
        "governance_access_audit_control_plane": "ready" if settings.governance_control_plane_enabled else "disabled",
        "production_certification_migration_recovery": "ready" if settings.production_certification_enabled else "disabled",
        "observability_slo_production_operations": "ready" if settings.observability_control_plane_enabled else "disabled",
        "incident_response_change_control_rollback": "ready" if settings.incident_change_control_enabled else "disabled",
        "continuity_backup_verification_disaster_recovery": "ready" if settings.continuity_disaster_recovery_enabled else "disabled",
        "multi_region_resilience_failover_coordination": "ready" if settings.multi_region_resilience_enabled else "disabled",
        "data_lifecycle_archival_integrity_preservation": "ready" if settings.data_lifecycle_preservation_enabled else "disabled",
        "federated_core_trusted_node_exchange": "ready" if settings.federation_trusted_node_exchange_enabled else "disabled",
        "capacity_forecasting_resource_governance": "ready" if settings.capacity_resource_governance_enabled else "disabled",
        "identity_credential_key_lifecycle": "ready" if settings.credential_key_lifecycle_enabled else "disabled",
        "scientific_object_storage_processing_adapter_fabric": "ready" if settings.scientific_object_storage_enabled else "disabled",
        "research_object_model_foundation": "ready" if settings.research_object_model_enabled else "disabled",
        "visual_reasoning_object_model": "ready" if settings.visual_reasoning_object_model_enabled else "disabled",
        "visualization_specification_renderer_registry": "ready" if settings.visualization_renderer_registry_enabled else "disabled",
        "system_maps": "ready" if settings.system_maps_enabled else "disabled",
        "flow_maps": "ready" if settings.flow_maps_enabled else "disabled",
        "scenario_landscapes": "ready" if settings.scenario_landscapes_enabled else "disabled",
        "interactive_model_canvas": "ready" if settings.interactive_model_canvas_enabled else "disabled",
        "scenario_compute_engine": "ready" if settings.scenario_compute_engine_enabled else "disabled",
        "uncertainty_sensitivity_ensemble_reasoning": "ready" if settings.uncertainty_reasoning_enabled else "disabled",
        "uncertainty_compute_runtime_integration": "ready" if settings.uncertainty_compute_runtime_enabled else "disabled",
        "causal_systems_explorer": "ready" if settings.causal_systems_explorer_enabled else "disabled",
        "spatial_temporal_visual_reasoning": "ready" if settings.spatial_temporal_visual_reasoning_enabled else "disabled",
        "research_librarian_visual_explanation": "ready" if settings.research_librarian_visual_explanation_enabled else "disabled",
        "cross_product_visual_research_objects": "ready" if settings.cross_product_visual_research_enabled else "disabled",
        "reproducible_visual_knowledge_layer": "ready" if settings.reproducible_visual_knowledge_enabled else "disabled",
        "visual_reasoning_runtime_scene_graph": "ready" if settings.visual_reasoning_runtime_enabled else "disabled",
        "open_forensics": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_timeline_event_reconstruction": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_spatial_temporal_evidence_integration": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_media_artifact_derivative_provenance": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_quantitative_reconstruction_reproduction_handoffs": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_testimony_statements_documentary_evidence": "ready" if settings.open_forensics_enabled else "disabled",
        "forensic_research_graph": "ready" if settings.open_forensics_enabled else "disabled",
        "reproducible_investigation_packages": "ready" if settings.open_forensics_enabled else "disabled",
        "external_provider_health_release_blocking": False,
        "services": [
            {
                "service_id": item["service_id"],
                "name": item["name"],
                "required": item["required"],
                "configured": item["configured"],
                "enabled": item["enabled"],
                "status": item["status"],
                "readiness": item["readiness"],
                "upstream_version": item.get("upstream_version"),
            }
            for item in gateway["services"]
        ],
    }


@router.get("/integration/readiness")
async def integration_readiness(request: Request):
    """Public-safe first-party integration status with no URLs or tokens."""
    gateway = await request.app.state.gateway_runtime.health_snapshot()
    settings = request.app.state.settings
    configuration_blockers: list[str] = []
    if settings.public_base_url_required:
        parsed = urlsplit(settings.public_base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            configuration_blockers.append("public_base_url")
    if (
        settings.required_cors_origin
        and settings.required_cors_origin not in settings.cors_origins
    ):
        configuration_blockers.append("required_cors_origin")
    release_ready = bool(gateway["release_ready"] and not configuration_blockers)
    return {
        "ok": release_ready,
        "core_version": settings.version,
        "public_base_url_configured": bool(settings.public_base_url),
        "required_cors_origin_configured": (
            not settings.required_cors_origin
            or settings.required_cors_origin in settings.cors_origins
        ),
        "configuration_blockers": configuration_blockers,
        "gateway": gateway["gateway"],
        "overall_status": gateway["overall_status"],
        "required_service_count": gateway["required_service_count"],
        "required_ready_count": gateway["required_ready_count"],
        "required_blockers": gateway["required_blockers"],
        "services": [
            {
                "service_id": item["service_id"],
                "name": item["name"],
                "required": item["required"],
                "configured": item["configured"],
                "enabled": item["enabled"],
                "status": item["status"],
                "readiness": item["readiness"],
                "upstream_version": item.get("upstream_version"),
            }
            for item in gateway["services"]
        ],
    }


@router.get(
    "/v1/meta",
    response_model=MetaResponse,
    dependencies=[Depends(require_read)],
)
def meta(request: Request):
    settings = request.app.state.settings
    return MetaResponse(
        name=settings.app_name,
        version=settings.version,
        environment=settings.environment,
        public_reads=settings.public_reads,
        write_auth_configured=bool(settings.write_api_key),
        max_graph_depth=settings.max_graph_depth,
        explorer_enabled=settings.explorer_enabled,
        capabilities=[
            "universal_entity_registry",
            "operational_evidence_facility_registry",
            "humanitarian_access_essential_services_fabric",
            "earth_ocean_space_scientific_service_fabric",
            "cross_product_evidence_exchange",
            "distributed_processing_storage_scale",
            "distributed_connector_workers",
            "server_sent_live_data_events",
            "governance_access_audit_control_plane",
            "production_certification_migration_recovery",
            "continuity_backup_verification_disaster_recovery",
            "multi_region_resilience_failover_coordination",
            "data_lifecycle_archival_integrity_preservation",
            "federated_core_trusted_node_exchange",
            "capacity_forecasting_resource_governance",
            "capacity_resource_profiles",
            "capacity_observation_windows",
            "bounded_linear_capacity_forecasts",
            "capacity_risk_assessments",
            "resource_budgets",
            "advisory_soft_limit_governance",
            "public_safe_capacity_status",
            "capacity_certification_gate",
            "identity_credential_key_lifecycle",
            "secret_free_credential_registry",
            "cryptographic_key_version_metadata",
            "credential_expiry_and_revocation",
            "overlap_aware_key_rotation",
            "service_credential_policy_metadata",
            "federation_webhook_dossier_key_lifecycle",
            "credential_use_audit_events",
            "public_safe_credential_health",
            "credential_lifecycle_certification_gate",
            "distributed_quota_admission_workload_governance",
            "database_shared_distributed_quota_backend",
            "per_subject_quota_budgets",
            "burst_quota_budgets",
            "workload_priority_classes",
            "weighted_fairness_policy",
            "expiring_concurrency_leases",
            "slo_aware_admission_control",
            "capacity_aware_admission_control",
            "hard_admission_rejection",
            "retry_after_guidance",
            "idempotent_admission_decisions",
            "public_safe_workload_governance_status",
            "workload_governance_certification_gate",
            "scientific_object_storage_processing_adapter_fabric",
            "research_object_model_foundation",
            "research_project_registry",
            "research_model_registry",
            "immutable_model_versions",
            "research_variables_and_parameters",
            "scenario_registry",
            "model_run_orchestration_records",
            "research_result_registry",
            "graph_native_research_objects",
            "provenance_linkable_model_runs",
            "lab_workbench_execution_boundary",
            "visual_reasoning_object_model",
            "renderer_neutral_visual_semantics",
            "visual_semantic_elements_and_relations",
            "visual_reasoning_layers",
            "visual_annotations_and_caveats",
            "source_entity_and_scientific_object_bindings",
            "immutable_visual_semantic_snapshots",
            "visual_snapshot_sha256_integrity",
            "visualization_specification_renderer_registry",
            "immutable_visualization_specifications",
            "renderer_contract_registry",
            "renderer_version_metadata",
            "renderer_compatibility_rules",
            "deterministic_renderer_resolution",
            "non_executing_renderer_resolution_records",
            "visualization_spec_sha256_integrity",
            "renderer_execution_external_to_core",
            "system_maps",
            "explicit_system_boundaries",
            "system_map_domains_and_memberships",
            "saved_system_map_views",
            "system_map_structural_validation",
            "system_map_visualization_spec_compilation",
            "system_map_layout_external_to_core",
            "system_map_causal_inference_not_automatic",
            "flow_maps",
            "typed_flow_channels",
            "relation_bound_directed_flows",
            "flow_quantity_uncertainty_metadata",
            "flow_node_state_observations",
            "unit_safe_flow_balance_summaries",
            "flow_map_structural_validation",
            "flow_map_visualization_spec_compilation",
            "flow_map_unit_conversion_not_automatic",
            "flow_map_simulation_not_automatic",
            "scenario_landscapes",
            "research_scenario_landscape_bindings",
            "scenario_baseline_and_comparison_roles",
            "scenario_comparison_dimensions",
            "scenario_uncertainty_aware_values",
            "baseline_relative_direct_numeric_summaries",
            "scenario_landscape_saved_views",
            "scenario_landscape_visualization_spec_compilation",
            "interactive_model_canvas",
            "model_bound_canvas_nodes",
            "model_canvas_dependency_edges",
            "governed_parameter_controls",
            "immutable_model_canvas_states",
            "external_model_execution_handoffs",
            "model_canvas_saved_views",
            "model_canvas_visualization_spec_compilation",
            "model_canvas_execution_external_to_core",
            "scenario_compute_engine",
            "reproducible_scenario_compute_plans",
            "scenario_compute_case_matrix",
            "scenario_parameter_override_validation",
            "scenario_parameter_bound_validation",
            "deterministic_scenario_input_manifests",
            "idempotent_scenario_execution_requests",
            "scenario_external_execution_attempt_ledger",
            "scenario_model_run_bindings",
            "scenario_result_bindings",
            "scenario_compute_lab_workbench_handoff",
            "scenario_compute_network_dispatch_external_to_core",
            "scenario_compute_numerical_execution_external_to_core",
            "uncertainty_definitions",
            "aleatory_epistemic_mixed_uncertainty",
            "governed_distribution_metadata",
            "sensitivity_studies",
            "sensitivity_factor_bindings",
            "externally_supplied_sensitivity_measures",
            "descriptive_sensitivity_rankings",
            "ensemble_reasoning",
            "ensemble_member_provenance",
            "externally_supplied_ensemble_statistics",
            "uncertainty_sampling_external_to_core",
            "sensitivity_algorithm_execution_external_to_core",
            "ensemble_aggregation_external_to_core",
            "uncertainty_compute_runtime_integration",
            "causal_systems_explorer",
            "spatial_temporal_visual_reasoning",
            "research_librarian_visual_explanation",
            "citation_aware_visual_explanations",
            "renderer_neutral_research_explanation_specs",
            "research_librarian_visual_handoff_contracts",
            "cross_product_visual_research_objects",
            "product_scoped_visual_research_members",
            "cross_product_semantic_relations",
            "reference_first_portable_visual_packages",
            "cross_product_product_identity_preservation",
            "cross_runtime_visual_research_handoffs",
            "deterministic_monte_carlo_sampling",
            "latin_hypercube_sampling",
            "sobol_design_and_index_analysis",
            "morris_design_and_elementary_effect_analysis",
            "ensemble_weight_normalization",
            "ensemble_descriptive_statistics",
            "empirical_probability_estimation",
            "lab_workbench_uncertainty_handoff_manifests",
            "scenario_execution_external_to_core",
            "scenario_ranking_not_automatic",
            "scenario_optimization_not_automatic",
            "scientific_storage_backend_registry",
            "scientific_local_object_store",
            "scientific_external_reference_store",
            "scientific_object_integrity_hashing",
            "scientific_derived_object_lineage",
            "scientific_processing_adapter_registry",
            "scientific_processing_run_ledger",
            "builtin_scientific_object_manifest_adapter",
            "credential_free_scientific_object_references",
            "public_safe_scientific_object_metadata",
            "preservation_manifest_integrity",
            "policy_and_legal_holds",
            "non_destructive_tombstone_lineage",
            "replication_aware_failover_assessment",
            "operator_coordinated_failover",
            "read_only_degraded_mode",
            "incident_response_change_control_rollback",
            "operator_confirmed_rollback",
            "incident_event_integrity_chain",
            "migration_assurance",
            "recovery_readiness_checkpoints",
            "policy_based_access_decisions",
            "tamper_evident_governance_audit",
            "governance_retention_policies",
            "partitioned_processing_jobs",
            "storage_object_registry",
            "backpressure_control",
            "retention_compaction",
            "reference_first_product_handoffs",
            "non_destructive_evidence_exchange",
            "scientific_domain_routing",
            "ocean_front_door_contract",
            "space_front_door_contract",
            "scientific_routing_non_truth_precedence",
            "controlled_predicate_registry",
            "relationship_review_workflow",
            "bounded_graph_traversal",
            "shortest_path_queries",
            "graph_backed_recommendations",
            "jsonld_entity_records",
            "public_knowledge_explorer",
            "claim_registry",
            "immutable_source_snapshots",
            "source_hash_verification",
            "evidence_records",
            "evidence_review_workflow",
            "evidence_review_assignments",
            "calculation_traces",
            "provenance_activities",
            "provenance_links",
            "tamper_evident_ledger",
            "ledger_chain_verification",
            "evidence_manifests",
            "public_evidence_explorer",
            "site_intelligence_manifest_import",
            "validation_event_foundation",
            "openapi",
            "python_client",
            "wordpress_client",
            "unified_public_api_v1",
            "unified_service_gateway",
            "environment_backed_service_registry",
            "aggregated_downstream_health",
            "cross_service_request_tracing",
            "bounded_service_proxy",
            "free_live_data_gateway",
            "free_source_acceptance_gate",
            "live_data_source_registry",
            "live_data_connector_sdk",
            "bounded_raw_response_cache",
            "normalized_live_observations",
            "data_freshness_classification",
            "source_license_and_attribution_registry",
            "live_data_provenance",
            "international_law_record_store",
            "united_nations_connector_pack",
            "legal_authority_classification",
            "scientific_data_connector_pack",
            "scientific_data_record_store",
            "economics_official_statistics_connector_pack",
            "economic_data_record_store",
            "sdmx_statistics_gateway",
            "company_filing_facts",
            "energy_statistics_ingestion",
            "geospatial_data_fabric",
            "portable_geojson_store",
            "postgis_expression_indexing",
            "bbox_spatial_queries",
            "geojson_feature_collections",
            "time_series_registry",
            "monthly_time_series_partition_keys",
            "scientific_asset_registry",
            "stac_1_0_catalog",
            "stac_item_search",
            "map_layer_registry",
            "wms_wmts_handoffs",
            "cog_pmtiles_asset_handoffs",
            "fits_netcdf_zarr_geoparquet_registry",
            "scientific_dataset_discovery",
            "astronomy_archive_discovery",
            "biomedical_and_chemical_discovery",
            "biodiversity_occurrence_discovery",
            "materials_science_discovery",
            "hydrology_observation_ingestion",
            "read_only_adql_gateway",
            "weather_reference_connector",
            "earth_observation_reference_connector",
            "hazard_event_reference_connector",
            "economic_indicator_reference_connectors",
            "sustainability_reference_connector",
            "per_service_circuit_breakers",
            "hashed_developer_credentials",
            "scoped_api_access",
            "plan_aware_rate_limits",
            "request_usage_records",
            "developer_applications",
            "developer_portal",
            "public_openapi",
            "python_public_sdk",
            "javascript_public_sdk",
            "postman_collection",
            "signed_webhooks",
            "webhook_delivery_outbox",
            "workflow_definition_registry",
            "ordered_end_to_end_workflows",
            "append_only_workflow_transitions",
            "signature_dossiers",
            "frozen_record_snapshots",
            "dossier_approvals",
            "platform_dossier_signatures",
            "dossier_signature_verification",
            "public_dossier_center",
            "public_trust_center",
            "evaluation_definition_registry",
            "immutable_evaluation_runs",
            "check_level_evaluation_results",
            "automated_trust_evaluators",
            "trust_findings",
            "public_incident_history",
            "known_limitation_registry",
            "trust_attestations",
            "machine_readable_trust_status",
            "trust_webhook_events",
        ],
        deferred_capabilities=[
            "large_scale_graph_database_adapter",
            "user_casebooks",
            "external_public_key_signature_verification",
            "qualified_electronic_signatures",
            "external_snapshot_object_storage_adapter",
            "developer_self_service_billing",
            "native_raster_processing_workers",
            "native_scientific_file_parsers",
        ],
    )


@router.get(
    "/v1/stats",
    response_model=RegistryStats,
    dependencies=[Depends(require_read)],
)
def stats(db: Session = Depends(get_session)):
    entity_rows = db.execute(
        select(Entity.entity_type, func.count(Entity.id))
        .group_by(Entity.entity_type)
        .order_by(Entity.entity_type)
    ).all()
    predicate_rows = db.execute(
        select(Relationship.predicate, func.count(Relationship.id))
        .group_by(Relationship.predicate)
        .order_by(Relationship.predicate)
    ).all()
    relationship_status_rows = db.execute(
        select(Relationship.status, func.count(Relationship.id))
        .group_by(Relationship.status)
        .order_by(Relationship.status)
    ).all()

    def count(model) -> int:
        return int(db.scalar(select(func.count()).select_from(model)) or 0)

    return RegistryStats(
        entities=count(Entity),
        relationships=count(Relationship),
        aliases=count(EntityAlias),
        predicate_definitions=count(PredicateDefinition),
        relationship_reviews=count(RelationshipReview),
        claims=count(ClaimRecord),
        source_snapshots=count(SourceSnapshot),
        evidence_records=count(EvidenceRecord),
        evidence_reviews=count(EvidenceReview),
        review_assignments=count(EvidenceReviewAssignment),
        provenance_activities=count(ProvenanceActivity),
        provenance_links=count(ProvenanceLink),
        calculation_traces=count(CalculationTrace),
        ledger_entries=count(LedgerEntry),
        evidence_foundations=count(EvidenceFoundation),
        validation_events=count(ValidationEvent),
        import_jobs=count(ImportJob),
        evaluation_definitions=count(EvaluationDefinition),
        evaluation_runs=count(EvaluationRun),
        evaluation_check_results=count(EvaluationCheckResult),
        trust_findings=count(TrustFinding),
        trust_incidents=count(TrustIncident),
        known_limitations=count(KnownLimitation),
        trust_attestations=count(TrustAttestation),
        live_data_sources=count(LiveDataSource),
        live_data_connectors=count(LiveDataConnector),
        live_data_ingestion_runs=count(LiveDataIngestionRun),
        live_data_observations=count(LiveDataObservation),
        international_law_records=count(InternationalLawRecord),
        scientific_data_records=count(ScientificDataRecord),
        economic_data_records=count(EconomicDataRecord),
        geospatial_features=count(GeospatialFeature),
        time_series_definitions=count(TimeSeriesDefinition),
        time_series_points=count(TimeSeriesPoint),
        scientific_data_assets=count(ScientificDataAsset),
        scientific_storage_backends=count(ScientificStorageBackend),
        scientific_stored_objects=count(ScientificStoredObject),
        scientific_processing_adapters=count(ScientificProcessingAdapter),
        scientific_processing_runs=count(ScientificProcessingRun),
        research_projects=count(ResearchProjectRecord),
        research_models=count(ResearchModelRecord),
        research_model_versions=count(ResearchModelVersionRecord),
        research_variables=count(ResearchVariableRecord),
        research_parameters=count(ResearchParameterRecord),
        research_scenarios=count(ResearchScenarioRecord),
        research_model_runs=count(ResearchModelRunRecord),
        research_results=count(ResearchResultRecord),
        visual_reasoning_objects=count(VisualReasoningObjectRecord),
        visual_reasoning_elements=count(VisualReasoningElementRecord),
        visual_reasoning_relations=count(VisualReasoningRelationRecord),
        visual_reasoning_layers=count(VisualReasoningLayerRecord),
        visual_reasoning_annotations=count(VisualReasoningAnnotationRecord),
        visual_reasoning_snapshots=count(VisualReasoningSnapshotRecord),
        cross_product_visual_research_objects=count(CrossProductVisualResearchObjectRecord),
        cross_product_visual_research_members=count(CrossProductVisualResearchMemberRecord),
        cross_product_visual_research_relations=count(CrossProductVisualResearchRelationRecord),
        cross_product_visual_research_views=count(CrossProductVisualResearchViewRecord),
        cross_product_visual_research_snapshots=count(CrossProductVisualResearchSnapshotRecord),
        reproducible_visual_knowledge_packages=count(ReproducibleVisualKnowledgePackageRecord),
        reproducible_visual_knowledge_inputs=count(ReproducibleVisualKnowledgeInputRecord),
        reproducible_visual_knowledge_environments=count(ReproducibleVisualKnowledgeEnvironmentRecord),
        reproducible_visual_knowledge_replay_plans=count(ReproducibleVisualKnowledgeReplayPlanRecord),
        reproducible_visual_knowledge_verifications=count(ReproducibleVisualKnowledgeVerificationRecord),
        reproducible_visual_knowledge_snapshots=count(ReproducibleVisualKnowledgeSnapshotRecord),
        forensic_investigations=count(ForensicInvestigationRecord),
        forensic_objects=count(ForensicObjectRecord),
        forensic_evidence_items=count(ForensicEvidenceItemRecord),
        forensic_evidence_source_bindings=count(ForensicEvidenceSourceBindingRecord),
        forensic_provenance_activities=count(ForensicProvenanceActivityRecord),
        forensic_object_relations=count(ForensicObjectRelationRecord),
        forensic_snapshots=count(ForensicSnapshotRecord),
        forensic_claims=count(ForensicClaimRecord),
        forensic_claim_evidence_assessments=count(ForensicClaimEvidenceAssessmentRecord),
        forensic_contradictions=count(ForensicContradictionRecord),
        forensic_hypotheses=count(ForensicHypothesisRecord),
        forensic_hypothesis_evidence_assessments=count(ForensicHypothesisEvidenceAssessmentRecord),
        forensic_hypothesis_relations=count(ForensicHypothesisRelationRecord),
        forensic_reasoning_snapshots=count(ForensicReasoningSnapshotRecord),
        forensic_events=count(ForensicEventRecord),
        forensic_event_evidence_bindings=count(ForensicEventEvidenceBindingRecord),
        forensic_event_participants=count(ForensicEventParticipantRecord),
        forensic_event_relations=count(ForensicEventRelationRecord),
        forensic_event_reconstructions=count(ForensicEventReconstructionRecord),
        forensic_timeline_views=count(ForensicTimelineViewRecord),
        forensic_timeline_snapshots=count(ForensicTimelineSnapshotRecord),
        forensic_media_artifacts=count(ForensicMediaArtifactRecord),
        forensic_media_derivations=count(ForensicMediaDerivativeRecord),
        forensic_media_metadata_records=count(ForensicMediaMetadataRecord),
        forensic_media_fingerprints=count(ForensicMediaFingerprintRecord),
        forensic_media_segments=count(ForensicMediaSegmentRecord),
        forensic_media_comparisons=count(ForensicMediaComparisonRecord),
        forensic_media_provenance_snapshots=count(ForensicMediaProvenanceSnapshotRecord),
        visualization_specifications=count(VisualizationSpecificationRecord),
        renderer_definitions=count(RendererDefinitionRecord),
        renderer_versions=count(RendererVersionRecord),
        renderer_compatibility_rules=count(RendererCompatibilityRuleRecord),
        renderer_resolutions=count(RendererResolutionRecord),
        system_maps=count(SystemMapRecord),
        system_map_boundaries=count(SystemMapBoundaryRecord),
        system_map_domains=count(SystemMapDomainRecord),
        system_map_memberships=count(SystemMapMembershipRecord),
        system_map_views=count(SystemMapViewRecord),
        flow_maps=count(FlowMapRecord),
        flow_map_channels=count(FlowMapChannelRecord),
        flow_map_flows=count(FlowMapFlowRecord),
        flow_map_node_states=count(FlowMapNodeStateRecord),
        flow_map_views=count(FlowMapViewRecord),
        scenario_landscapes=count(ScenarioLandscapeRecord),
        scenario_landscape_scenarios=count(ScenarioLandscapeScenarioRecord),
        scenario_landscape_dimensions=count(ScenarioLandscapeDimensionRecord),
        scenario_landscape_values=count(ScenarioLandscapeValueRecord),
        scenario_landscape_views=count(ScenarioLandscapeViewRecord),
        model_canvases=count(ModelCanvasRecord),
        model_canvas_nodes=count(ModelCanvasNodeRecord),
        model_canvas_edges=count(ModelCanvasEdgeRecord),
        model_canvas_controls=count(ModelCanvasControlRecord),
        model_canvas_states=count(ModelCanvasStateRecord),
        model_canvas_views=count(ModelCanvasViewRecord),
        scenario_compute_plans=count(ScenarioComputePlanRecord),
        scenario_compute_cases=count(ScenarioComputeCaseRecord),
        scenario_compute_requests=count(ScenarioComputeRequestRecord),
        scenario_compute_attempts=count(ScenarioComputeAttemptRecord),
        scenario_compute_result_bindings=count(ScenarioComputeResultBindingRecord),
        uncertainty_definitions=count(UncertaintyDefinitionRecord),
        sensitivity_studies=count(SensitivityStudyRecord),
        sensitivity_factors=count(SensitivityFactorRecord),
        sensitivity_measures=count(SensitivityMeasureRecord),
        ensembles=count(EnsembleRecord),
        ensemble_members=count(EnsembleMemberRecord),
        ensemble_statistics=count(EnsembleStatisticRecord),
        uncertainty_compute_runs=count(UncertaintyComputeRunRecord),
        map_layers=count(MapLayer),
        stac_collections=count(StacCollection),
        stac_items=count(StacItem),
        entities_by_type={key: int(value) for key, value in entity_rows},
        relationships_by_predicate={
            key: int(value) for key, value in predicate_rows
        },
        relationships_by_status={
            key: int(value) for key, value in relationship_status_rows
        },
    )
