from app.database import Database
from app.migrations import run_migrations,migration_status
from app.services import research_contributor_provenance as svc

def session(tmp_path):
 db=Database("sqlite:///"+str(tmp_path/"contributors.db")); run_migrations(db); return db,db.session_factory()
def human(s,key="human",visibility="public"):
 return svc.create_contributor(s,{"contributor_key":key,"display_name":"Researcher "+key,"actor_type":"human","visibility":visibility})["id"]
def test_readiness_and_boundaries(tmp_path):
 db,s=session(tmp_path); d=svc.readiness(s); assert d["release"]=="2.93.0" and "0097" in migration_status(db)["applied"] and migration_status(db)["pending"]==[]; assert d["contributor_registry_by_core"] is True and d["execute_agent_actions_by_core"] is False and d["decide_credit_by_core"] is False and d["determine_truth_by_core"] is False; s.close()
def test_human_role_and_credit_contribution(tmp_path):
 db,s=session(tmp_path); c=human(s,"lead"); r=svc.create_role_definition(s,{"role_key":"credit-methodology","label":"Methodology","role_category":"credit","taxonomy_ref":"CRediT:Methodology"}); a=svc.assign_role(s,{"assignment_key":"a1","contributor_id":c,"role_definition_id":r["id"],"scope_type":"project","scope_ref":"project:1","visibility":"public"}); x=svc.record_contribution(s,{"contribution_key":"c1","contributor_id":c,"role_assignment_id":a["id"],"project_ref":"project:1","contribution_type":"methodology","action_type":"protocol_design","product_key":"core","object_type":"protocol","object_ref":"protocol:1","inputs":["question:1"],"outputs":["protocol:1"],"visibility":"public"}); assert x["contribution_type"]=="methodology" and x["object_ref"]=="protocol:1"; s.close()
def test_controlled_agent_action_provenance(tmp_path):
 db,s=session(tmp_path); c=svc.create_contributor(s,{"contributor_key":"stat-agent","display_name":"Statistician Agent","actor_type":"ai_agent","visibility":"public"}); p=svc.create_agent_profile(s,{"agent_key":"agent:stats","contributor_id":c["id"],"specialist_role":"statistician","provider_ref":"provider:test","model_ref":"model:test","configuration_hash":"a"*64,"human_supervisor_ref":"person:pi","allowed_actions":["analyze_declared_dataset"],"visibility":"public"}); con=svc.record_contribution(s,{"contribution_key":"agent-contrib","contributor_id":c["id"],"project_ref":"project:agent","contribution_type":"formal_analysis","action_type":"statistical_analysis","product_key":"workspace","object_type":"execution","object_ref":"execution:1","tool_ref":"python","runtime_ref":"python:3.12","model_ref":"model:test","visibility":"public"}); act=svc.record_agent_action(s,{"action_key":"action:1","agent_profile_id":p["id"],"contribution_id":con["id"],"project_ref":"project:agent","action_type":"analyze","inputs":["dataset:v1"],"outputs":["result:1"],"tool_ref":"python","runtime_ref":"python:3.12","model_ref":"model:test","human_review_status":"reviewed","visibility":"public"}); assert act["human_review_status"]=="reviewed" and act["model_ref"]=="model:test"; s.close()
def test_authorship_responsibility_and_review(tmp_path):
 db,s=session(tmp_path); a=human(s,"author"); reviewer=human(s,"reviewer"); con=svc.record_contribution(s,{"contribution_key":"writing","contributor_id":a,"project_ref":"project:pub","contribution_type":"writing_original_draft","action_type":"draft","product_key":"library","object_type":"publication","object_ref":"publication:1","visibility":"public"}); au=svc.assert_authorship(s,{"assertion_key":"author-1","contributor_id":a,"project_ref":"project:pub","publication_ref":"publication:1","authorship_type":"author","contribution_statement":"Drafted methods and results.","visibility":"public"}); rs=svc.declare_responsibility(s,{"statement_key":"resp-1","contributor_id":a,"project_ref":"project:pub","scope_type":"publication","scope_ref":"publication:1","responsibility_type":"content_accountability","statement":"Responsible for declared sections.","visibility":"public"}); rv=svc.review_contribution(s,{"review_key":"review-1","contribution_id":con["id"],"reviewer_contributor_id":reviewer,"project_ref":"project:pub","review_type":"editorial","status":"recorded","visibility":"public"}); assert au["publication_ref"]=="publication:1" and rs["responsibility_type"]=="content_accountability" and rv["reviewer_contributor_id"]==reviewer; s.close()
def test_revision_snapshot_and_guardrails(tmp_path):
 db,s=session(tmp_path); c=human(s,"rev",visibility="internal"); r=svc.revise(s,{"project_ref":"project:rev","contributor_id":c,"change_type":"affiliation","prior_state":{"affiliation":"a"},"revised_state":{"affiliation":"b"}}); assert r["revision"]==1; a=svc.snapshot(s,{"project_ref":"project:rev"}); b=svc.snapshot(s,{"project_ref":"project:rev"}); assert b["previous_snapshot_hash"]==a["content_hash"]
 try: svc.revise(s,{"project_ref":"project:rev","decide_credit_by_core":True}); assert False
 except ValueError: pass
 s.close()
def test_public_redaction_and_lineage(tmp_path):
 db,s=session(tmp_path); public=human(s,"public",visibility="public"); private=human(s,"private",visibility="internal"); svc.record_contribution(s,{"contribution_key":"pub","contributor_id":public,"project_ref":"project:redact","contribution_type":"investigation","action_type":"collect","product_key":"library","object_type":"evidence","object_ref":"evidence:1","visibility":"public"}); svc.record_contribution(s,{"contribution_key":"priv","contributor_id":private,"project_ref":"project:redact","contribution_type":"data_curation","action_type":"curate","product_key":"catalyst_data","object_type":"dataset","object_ref":"dataset:secret","visibility":"internal"}); b=svc.bundle(s,"project:redact",True); assert [x["contributor_key"] for x in b["contributors"]]==["public"] and [x["contribution_key"] for x in b["contributions"]]==["pub"] and b["revisions"]==[]; l=svc.lineage(s,"project:redact",True); assert l["lineage_is_declared_not_inferred"] is True and any(e["relation"]=="declared_contributor" for e in l["edges"]); s.close()
