from fastapi.testclient import TestClient

from app.config import Settings
from app.main import create_app


def client(tmp_path):
    return TestClient(create_app(Settings(database_url="sqlite:///" + str(tmp_path / "arg.db"))))


def project(c, visibility="public"):
    response = c.post(
        "/v1/research/projects",
        json={"data": {"title": "Argument Synthesis Study", "project_key": "argument-synthesis-study", "visibility": visibility}},
    )
    assert response.status_code == 200, response.text
    return response.json()["project"]["id"]


def test_readiness(tmp_path):
    c = client(tmp_path)
    data = c.get("/v1/research/arguments/readiness").json()
    assert data["release"] == "2.79.0"
    assert data["contract"] == "sc.research.argument-evidentiary-synthesis.v1"
    assert data["migration_0083_applied"] is True
    assert data["declared_argument_graph_by_core"] is True
    assert data["descriptive_coverage_summary_by_core"] is True
    assert data["generate_argument_by_core"] is False
    assert data["rank_arguments_by_core"] is False
    assert data["infer_truth_by_core"] is False
    c.close()


def test_argument_synthesis_roundtrip(tmp_path):
    c = client(tmp_path)
    pid = project(c)
    arg = c.post(
        f"/v1/research/arguments/projects/{pid}",
        json={"data": {
            "argument_key": "argument-1",
            "title": "Evidence-based interpretation",
            "thesis_text": "The registered findings support a bounded interpretation.",
            "central_claim_ref": "claim:central",
            "argument_type": "analytical",
        }},
    )
    assert arg.status_code == 200, arg.text
    aid = arg.json()["id"]

    evidence = c.post(
        f"/v1/research/arguments/{aid}/nodes",
        json={"data": {
            "node_key": "evidence-1",
            "node_type": "evidence",
            "role": "premise",
            "source_ref": "evidence:1",
            "citation_refs": ["source:1"],
        }},
    )
    assert evidence.status_code == 200, evidence.text
    evidence_id = evidence.json()["id"]

    claim = c.post(
        f"/v1/research/arguments/{aid}/nodes",
        json={"data": {
            "node_key": "claim-1",
            "node_type": "claim",
            "role": "conclusion",
            "source_ref": "claim:central",
            "statement_text": "Researcher-authored claim statement.",
        }},
    )
    assert claim.status_code == 200, claim.text
    claim_id = claim.json()["id"]

    edge = c.post(
        f"/v1/research/arguments/{aid}/edges",
        json={"data": {
            "edge_key": "e1-c1",
            "source_node_id": evidence_id,
            "target_node_id": claim_id,
            "relation": "supports",
            "rationale": "Researcher-declared support relation.",
            "evidence_refs": ["evidence:1"],
        }},
    )
    assert edge.status_code == 200, edge.text

    synthesis = c.post(
        f"/v1/research/arguments/{aid}/syntheses",
        json={"data": {
            "synthesis_key": "syn-1",
            "title": "Registered evidentiary synthesis",
            "synthesis_type": "evidentiary",
            "synthesis_text": "This synthesis is supplied by the researcher, not generated by Core.",
            "uncertainty": {"note": "bounded by available sources"},
        }},
    )
    assert synthesis.status_code == 200, synthesis.text
    sid = synthesis.json()["id"]

    component = c.post(
        f"/v1/research/arguments/syntheses/{sid}/components",
        json={"data": {
            "component_key": "component-1",
            "source_type": "evidence",
            "source_ref": "evidence:1",
            "role": "primary_evidence",
            "researcher_note": "Included because it directly bears on the claim.",
        }},
    )
    assert component.status_code == 200, component.text

    counter = c.post(
        f"/v1/research/arguments/{aid}/counterarguments",
        json={"data": {
            "counterargument_key": "counter-1",
            "statement_text": "An alternative interpretation remains possible.",
            "responds_to_node_id": claim_id,
            "evidence_refs": ["evidence:2"],
            "status": "open",
        }},
    )
    assert counter.status_code == 200, counter.text

    tension = c.post(
        f"/v1/research/arguments/{aid}/tensions",
        json={"data": {
            "tension_key": "tension-1",
            "title": "Conflicting observations",
            "description": "Evidence records are not fully consistent.",
            "source_refs": ["evidence:1", "evidence:2"],
            "status": "open",
        }},
    )
    assert tension.status_code == 200, tension.text

    rev = c.post(
        f"/v1/research/arguments/{aid}/revisions",
        json={"data": {
            "status": "active",
            "limitations": ["Limited to the registered study scope."],
            "change_summary": "Activated argument after evidentiary mapping.",
        }},
    )
    assert rev.status_code == 200, rev.text
    assert rev.json()["revision"] == 1
    assert len(rev.json()["state_hash"]) == 64

    amap = c.get(f"/v1/research/arguments/{aid}/map")
    assert amap.status_code == 200, amap.text
    m = amap.json()
    assert len(m["nodes"]) == 2
    assert len(m["edges"]) == 1
    assert m["descriptive_coverage"]["node_type_counts"]["evidence"] == 1
    assert m["descriptive_coverage"]["edge_relation_counts"]["supports"] == 1
    assert m["descriptive_coverage"]["counterargument_count"] == 1
    assert m["descriptive_coverage"]["open_tension_count"] == 1
    assert m["coverage_is_descriptive_only"] is True
    assert m["evidence_scores_computed"] is False
    assert m["argument_ranking_computed"] is False
    assert m["truth_determination_performed"] is False

    s1 = c.post(f"/v1/research/arguments/{aid}/snapshots", json={"data": {}}).json()
    s2 = c.post(f"/v1/research/arguments/{aid}/snapshots", json={"data": {}}).json()
    assert s2["previous_snapshot_hash"] == s1["content_hash"]

    bundle = c.get(f"/v1/research/arguments/{aid}/bundle")
    assert bundle.status_code == 200, bundle.text
    b = bundle.json()
    assert len(b["nodes"]) == 2
    assert len(b["edges"]) == 1
    assert len(b["syntheses"]) == 1
    assert len(b["synthesis_components"]) == 1
    assert len(b["counterarguments"]) == 1
    assert len(b["tensions"]) == 1
    assert len(b["argument_revisions"]) == 1
    assert len(b["snapshots"]) == 2
    assert b["generate_synthesis_by_core"] is False
    assert b["score_evidence_by_core"] is False
    c.close()


def test_boundaries(tmp_path):
    c = client(tmp_path)
    pid = project(c)
    bad = c.post(
        f"/v1/research/arguments/projects/{pid}",
        json={"data": {
            "argument_key": "bad",
            "title": "Bad",
            "generate_argument_by_core": True,
        }},
    )
    assert bad.status_code == 422
    c.close()
