from app.database import Database
from app.migrations import run_migrations,migration_status
from app.services import scholarly_interoperability as svc
def session(tmp_path):
 db=Database("sqlite:///"+str(tmp_path/"interop.db")); run_migrations(db); return db,db.session_factory()
def pkg(s,project="project:1",visibility="public"):
 return svc.create_package(s,{"package_key":"pkg:"+project,"project_ref":project,"package_type":"research_compendium","title":"Research package","package_profile":"ro-crate","visibility":visibility})
def test_readiness_and_boundaries(tmp_path):
 db,s=session(tmp_path); d=svc.readiness(s); assert d["release"]=="2.95.0" and "0099" in migration_status(db)["applied"] and migration_status(db)["pending"]==[]; assert d["scholarly_package_registry_by_core"] is True and d["mint_identifier_by_core"] is False and d["publish_package_by_core"] is False and d["determine_truth_by_core"] is False; s.close()
def test_package_citation_and_identifiers(tmp_path):
 db,s=session(tmp_path); p=pkg(s); m=svc.add_member(s,{"member_key":"m1","package_id":p["id"],"project_ref":"project:1","member_type":"dataset","object_ref":"dataset:1","object_version_ref":"v3","content_hash":"abc","visibility":"public"}); c=svc.add_citation(s,{"citation_key":"c1","package_id":p["id"],"project_ref":"project:1","cited_object_ref":"article:1","citation_format":"csl-json","citation_data":{"title":"Source"},"visibility":"public"}); i=svc.add_identifier(s,{"identifier_key":"i1","package_id":p["id"],"project_ref":"project:1","object_ref":"publication:1","scheme":"doi","identifier":"10.1234/example","status":"declared","visibility":"public"}); assert m["object_version_ref"]=="v3" and c["citation_format"]=="csl-json" and i["scheme"]=="doi"; s.close()
def test_dataset_notebook_manifest_metadata_export(tmp_path):
 db,s=session(tmp_path); p=pkg(s,"project:artifacts"); d=svc.add_dataset(s,{"dataset_key":"d1","package_id":p["id"],"project_ref":"project:artifacts","dataset_ref":"dataset:climate","version_ref":"2026-09","content_hash":"deadbeef","media_type":"text/csv","visibility":"public"}); n=svc.add_notebook(s,{"notebook_key":"n1","package_id":p["id"],"project_ref":"project:artifacts","notebook_ref":"notebook:analysis","notebook_format":"ipynb","environment_ref":"env:1","execution_ref":"execution:1","visibility":"public"}); pm=svc.add_manifest(s,{"manifest_key":"pm1","package_id":p["id"],"project_ref":"project:artifacts","standard":"ro-crate","bindings":[{"ref":"dataset:climate","hash":"deadbeef"}],"visibility":"public"}); md=svc.add_metadata_profile(s,{"profile_key":"md1","package_id":p["id"],"project_ref":"project:artifacts","standard":"datacite","metadata":{"creators":["researcher:1"]},"visibility":"public"}); ex=svc.add_export_profile(s,{"export_key":"e1","package_id":p["id"],"project_ref":"project:artifacts","export_format":"ro-crate","filename":"package.zip","visibility":"public"}); assert d["version_ref"]=="2026-09" and n["environment_ref"]=="env:1" and len(pm["manifest_hash"])==64 and md["standard"]=="datacite" and ex["export_format"]=="ro-crate"; s.close()
def test_publication_binding_external_validation_revision_snapshot(tmp_path):
 db,s=session(tmp_path); p=pkg(s,"project:publication"); b=svc.bind_publication_object(s,{"binding_key":"pb1","package_id":p["id"],"project_ref":"project:publication","publication_ref":"publication:81","object_type":"figure","object_ref":"figure:1","role":"figure","visibility":"public"}); v=svc.record_validation(s,{"validation_key":"v1","package_id":p["id"],"project_ref":"project:publication","validator_ref":"tool:ro-crate-validator","validation_type":"schema_conformance","status":"passed_external","evidence":["report:1"],"visibility":"public"}); r=svc.revise(s,{"project_ref":"project:publication","package_id":p["id"],"prior_state":{"status":"draft"},"revised_state":{"status":"frozen"}}); a=svc.snapshot(s,{"project_ref":"project:publication"}); z=svc.snapshot(s,{"project_ref":"project:publication"}); assert b["object_ref"]=="figure:1" and v["validator_ref"]=="tool:ro-crate-validator" and r["revision"]==1 and z["previous_snapshot_hash"]==a["content_hash"]; s.close()
def test_public_redaction_lineage_and_guardrails(tmp_path):
 db,s=session(tmp_path); p=pkg(s,"project:redact","public"); q=svc.create_package(s,{"package_key":"private","project_ref":"project:redact","package_type":"data_package","title":"Private","visibility":"internal"}); svc.add_member(s,{"member_key":"pub","package_id":p["id"],"project_ref":"project:redact","member_type":"dataset","object_ref":"dataset:public","visibility":"public"}); svc.add_member(s,{"member_key":"priv","package_id":q["id"],"project_ref":"project:redact","member_type":"dataset","object_ref":"dataset:private","visibility":"internal"}); b=svc.bundle(s,"project:redact",True); assert [x["package_key"] for x in b["packages"]]==["pkg:project:redact"] and [x["object_ref"] for x in b["members"]]==["dataset:public"] and b["revisions"]==[]; assert svc.lineage(s,"project:redact",True)["lineage_is_declared_not_inferred"] is True
 try: svc.create_package(s,{"package_key":"bad","project_ref":"project:redact","package_type":"research_compendium","title":"Bad","mint_identifier_by_core":True}); assert False
 except ValueError: pass
 s.close()
