from app.database import Database
from app.migrations import run_migrations,migration_status
from app.services import unified_research_runtime as svc

def session(tmp_path):
    db=Database("sqlite:///"+str(tmp_path/"runtime.db")); run_migrations(db); return db,db.session_factory()
def contract(s,visibility="public"):
    return svc.create_contract(s,{"contract_key":"core-runtime-v1","title":"Unified research runtime","contract_version":"1.0","required_capabilities":["object:read","object:version","provenance:trace"],"visibility":visibility})
def test_readiness_and_boundaries(tmp_path):
    db,s=session(tmp_path); r=svc.readiness(s); st=migration_status(db); assert r["release"]=="2.96.0" and "0100" in st["applied"] and st["pending"]==[]; assert r["runtime_contract_registry_by_core"] is True and r["execute_specialist_work_by_core"] is False and r["determine_truth_by_core"] is False; s.close()
def test_contract_object_operation_capability(tmp_path):
    db,s=session(tmp_path); c=contract(s); o=svc.add_object_type(s,{"object_type_key":"finding","contract_id":c["id"],"object_family":"research_finding","schema_ref":"schema:finding-v1","canonical_api_ref":"/v1/research/intelligence/findings","visibility":"public"}); op=svc.add_operation(s,{"operation_key":"finding-read","contract_id":c["id"],"operation":"read","object_type_ref":"finding","method":"GET","path_template":"/v1/research/intelligence/findings/{id}","idempotent":True,"visibility":"public"}); cap=svc.add_capability(s,{"capability_key":"trace","contract_id":c["id"],"capability":"provenance:trace","visibility":"public"}); assert o["object_family"]=="research_finding" and op["operation"]=="read" and cap["capability"]=="provenance:trace"; s.close()
def test_product_binding_and_deterministic_compatibility(tmp_path):
    db,s=session(tmp_path); c=contract(s); b=svc.bind_product(s,{"binding_key":"workspace","contract_id":c["id"],"product_ref":"product:workspace","product_version":"2.x","supported_capabilities":["object:read","object:version","provenance:trace","context:handoff"],"supported_object_types":["finding","claim"],"visibility":"public"}); rep=svc.compatibility_report(s,c["id"],b["id"]); assert rep["declared_compatibility"] is True and rep["missing_declared_capabilities"]==[] and rep["compatibility_is_deterministic_from_declared_capabilities_not_certification"] is True; s.close()
def test_exchange_invocation_result_lineage(tmp_path):
    db,s=session(tmp_path); c=contract(s); e=svc.create_exchange(s,{"exchange_key":"ex1","contract_id":c["id"],"project_ref":"project:1","source_product_ref":"product:library","target_product_ref":"product:workbench","operation":"handoff","object_refs":["dataset:1","protocol:1"],"context_ref":"context:1","workflow_ref":"workflow:1","provenance_refs":["prov:1"],"visibility":"public"}); i=svc.record_invocation(s,{"invocation_key":"inv1","contract_id":c["id"],"project_ref":"project:1","exchange_id":e["id"],"caller_ref":"product:workbench","operation":"read","input_refs":["dataset:1"],"runtime_ref":"runtime:python-3.12","visibility":"public"}); r=svc.bind_result(s,{"result_key":"res1","invocation_id":i["id"],"project_ref":"project:1","result_type":"analysis_output","object_ref":"result:1","object_version_ref":"v1","content_hash":"abc","visibility":"public"}); b=svc.project_bundle(s,"project:1",True); assert len(e["envelope_hash"])==64 and r["object_ref"]=="result:1" and len(b["exchanges"])==1 and len(b["results"])==1; s.close()
def test_compatibility_assertion_revision_snapshot(tmp_path):
    db,s=session(tmp_path); c=contract(s); b=svc.bind_product(s,{"binding_key":"lab","contract_id":c["id"],"product_ref":"product:lab","supported_capabilities":["object:read"],"visibility":"public"}); a=svc.record_compatibility(s,{"assertion_key":"a1","contract_id":c["id"],"product_binding_id":b["id"],"asserted_by":"test:conformance-suite","status":"partial","checks":[{"name":"read","status":"pass"}],"evidence_refs":["report:1"],"visibility":"public"}); rev=svc.revise(s,{"contract_id":c["id"],"prior_state":{"version":"1.0"},"revised_state":{"version":"1.0.1"}}); x=svc.snapshot(s,{"contract_id":c["id"]}); y=svc.snapshot(s,{"contract_id":c["id"]}); assert a["status"]=="partial" and rev["revision"]==1 and y["previous_snapshot_hash"]==x["content_hash"]; s.close()
def test_public_redaction_and_guardrails(tmp_path):
    db,s=session(tmp_path); c=contract(s,"public"); svc.add_capability(s,{"capability_key":"public","contract_id":c["id"],"capability":"object:read","visibility":"public"}); svc.add_capability(s,{"capability_key":"private","contract_id":c["id"],"capability":"object:update","visibility":"internal"}); b=svc.contract_bundle(s,c["id"],True); assert [x["capability_key"] for x in b["capabilities"]]==["public"] and b["revisions"]==[] and b["snapshots"]==[]
    try: svc.create_contract(s,{"contract_key":"bad","title":"bad","execute_specialist_work_by_core":True}); assert False
    except ValueError: pass
    s.close()
