from app.database import Database
from app.migrations import run_migrations,migration_status
from app.services import research_validation_challenge as svc

def session(tmp_path):
 db=Database("sqlite:///"+str(tmp_path/"validation.db")); run_migrations(db); return db,db.session_factory()
def challenge(s,project="project:1",visibility="public"):
 return svc.create_challenge(s,{"challenge_key":"challenge:"+project,"project_ref":project,"challenge_type":"alternative_hypothesis","title":"Challenge assumptions","visibility":visibility})
def test_readiness_and_boundaries(tmp_path):
 db,s=session(tmp_path); d=svc.readiness(s); assert d["release"]=="2.94.0" and "0098" in migration_status(db)["applied"] and migration_status(db)["pending"]==[]; assert d["validation_challenge_registry_by_core"] is True and d["resolve_hypotheses_by_core"] is False and d["certify_validity_by_core"] is False and d["determine_truth_by_core"] is False; s.close()
def test_alternatives_contradiction_and_counterevidence(tmp_path):
 db,s=session(tmp_path); c=challenge(s); svc.bind_target(s,{"target_key":"t1","challenge_id":c["id"],"project_ref":"project:1","target_type":"claim","target_ref":"claim:1","visibility":"public"}); h=svc.add_alternative_hypothesis(s,{"hypothesis_key":"h-alt","challenge_id":c["id"],"project_ref":"project:1","statement":"Alternative explanation","distinguishing_evidence":["evidence:2"],"visibility":"public"}); x=svc.record_contradiction_test(s,{"test_key":"ct1","challenge_id":c["id"],"project_ref":"project:1","assertion_a_ref":"claim:1","assertion_b_ref":"claim:2","result_status":"tension_recorded","evidence":["evidence:3"],"visibility":"public"}); e=svc.record_counterevidence(s,{"counterevidence_key":"ce1","challenge_id":c["id"],"project_ref":"project:1","evidence_ref":"evidence:4","challenges_ref":"claim:1","visibility":"public"}); assert h["statement"]=="Alternative explanation" and x["result_status"]=="tension_recorded" and e["challenges_ref"]=="claim:1"; s.close()
def test_sensitivity_robustness_replication(tmp_path):
 db,s=session(tmp_path); c=challenge(s,"project:checks"); a=svc.record_sensitivity_check(s,{"check_key":"s1","challenge_id":c["id"],"project_ref":"project:checks","target_ref":"inference:1","factor_ref":"parameter:alpha","method_ref":"sobol","execution_ref":"execution:1","result_ref":"result:1","outcome":"recorded","visibility":"public"}); b=svc.record_robustness_check(s,{"check_key":"r1","challenge_id":c["id"],"project_ref":"project:checks","target_ref":"finding:1","variant_type":"alternate_specification","method_ref":"method:2","outcome":"recorded","visibility":"public"}); r=svc.record_replication_attempt(s,{"attempt_key":"rep1","challenge_id":c["id"],"project_ref":"project:checks","target_ref":"study:1","protocol_ref":"protocol:2","execution_ref":"execution:rep","result_status":"recorded","visibility":"public"}); assert a["method_ref"]=="sobol" and b["variant_type"]=="alternate_specification" and r["protocol_ref"]=="protocol:2"; s.close()
def test_reviewer_response_revision_snapshot(tmp_path):
 db,s=session(tmp_path); c=challenge(s,"project:review"); rc=svc.record_reviewer_challenge(s,{"review_challenge_key":"rc1","challenge_id":c["id"],"project_ref":"project:review","reviewer_ref":"contributor:reviewer","review_ref":"peer-review:1","target_ref":"publication:1","challenge_statement":"Explain robustness.","visibility":"public"}); rp=svc.respond(s,{"response_key":"resp1","challenge_id":c["id"],"project_ref":"project:review","responder_ref":"contributor:author","statement":"Added sensitivity analysis.","revised_object_ref":"publication:2","visibility":"public"}); rv=svc.revise(s,{"project_ref":"project:review","challenge_id":c["id"],"prior_state":{"status":"open"},"revised_state":{"status":"responded"}}); a=svc.snapshot(s,{"project_ref":"project:review"}); b=svc.snapshot(s,{"project_ref":"project:review"}); assert rc["target_ref"]=="publication:1" and rp["revised_object_ref"]=="publication:2" and rv["revision"]==1 and b["previous_snapshot_hash"]==a["content_hash"]; s.close()
def test_public_redaction_lineage_and_guardrails(tmp_path):
 db,s=session(tmp_path); pub=challenge(s,"project:redact","public"); priv=svc.create_challenge(s,{"challenge_key":"private","project_ref":"project:redact","challenge_type":"counterevidence","title":"Private challenge","visibility":"internal"}); svc.bind_target(s,{"target_key":"pub-target","challenge_id":pub["id"],"project_ref":"project:redact","target_type":"claim","target_ref":"claim:public","visibility":"public"}); svc.bind_target(s,{"target_key":"priv-target","challenge_id":priv["id"],"project_ref":"project:redact","target_type":"claim","target_ref":"claim:private","visibility":"internal"}); b=svc.bundle(s,"project:redact",True); assert [x["challenge_key"] for x in b["challenges"]]==["challenge:project:redact"] and [x["target_ref"] for x in b["targets"]]==["claim:public"] and b["revisions"]==[]; assert svc.lineage(s,"project:redact",True)["lineage_is_declared_not_inferred"] is True
 try: svc.revise(s,{"project_ref":"project:redact","resolve_hypotheses_by_core":True}); assert False
 except ValueError: pass
 s.close()
