from __future__ import annotations

DEFAULT_API_PLANS: list[dict] = [
    {
        "id": "free",
        "name": "Public Research",
        "description": "Free read access for public-interest research, prototypes, and noncommercial integrations.",
        "requests_per_minute": 60,
        "requests_per_day": 5000,
        "max_page_size": 100,
        "allowed_scopes": [
            "public:status",
            "registry:read",
            "graph:read",
            "evidence:read",
            "ledger:read",
            "trust:read",
            "workflow:read",
            "dossier:read",
            "gateway:read",
            "data:read",
            "developer:read",
            "webhooks:manage",
        ],
        "public": True,
        "active": True,
        "sort_order": 10,
        "metadata": {"price": "free", "intended_use": "public-interest"},
    },
    {
        "id": "standard",
        "name": "Standard Integration",
        "description": "Higher quotas for sustained organizational and product integrations.",
        "requests_per_minute": 300,
        "requests_per_day": 50000,
        "max_page_size": 200,
        "allowed_scopes": [
            "public:status",
            "registry:read",
            "graph:read",
            "evidence:read",
            "ledger:read",
            "trust:read",
            "workflow:read",
            "dossier:read",
            "gateway:read",
            "data:read",
            "developer:read",
            "webhooks:manage",
        ],
        "public": True,
        "active": True,
        "sort_order": 20,
        "metadata": {"price": "reviewed", "intended_use": "production"},
    },
    {
        "id": "internal",
        "name": "Sustainable Catalyst Internal",
        "description": "Internal product-to-product integration plan.",
        "requests_per_minute": 2000,
        "requests_per_day": 500000,
        "max_page_size": 1000,
        "allowed_scopes": [
            "public:status",
            "registry:read",
            "graph:read",
            "evidence:read",
            "ledger:read",
            "trust:read",
            "workflow:read",
            "dossier:read",
            "gateway:read",
            "data:read",
            "developer:read",
            "webhooks:manage",
        ],
        "public": False,
        "active": True,
        "sort_order": 100,
        "metadata": {"price": "internal"},
    },
]
