from __future__ import annotations

from datetime import datetime, timezone

REVIEWED_AT = datetime(2026, 7, 14, tzinfo=timezone.utc)

DEFAULT_LIVE_DATA_SOURCES: list[dict] = [
    {
        "id": "met-norway",
        "name": "MET Norway Weather API",
        "organization": "Norwegian Meteorological Institute",
        "description": "Official global forecast data and related meteorological services.",
        "homepage_url": "https://api.met.no/",
        "documentation_url": "https://api.met.no/weatherapi/locationforecast/2.0/documentation",
        "license_name": "Creative Commons attribution terms; provider terms apply",
        "license_url": "https://api.met.no/doc/TermsOfService",
        "attribution": "Norwegian Meteorological Institute",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_with_attribution",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed_with_identifying_user_agent",
        "rate_limit_summary": "Cache responses and identify the application with a contact-bearing User-Agent.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "Norway"},
    },
    {
        "id": "nasa-earthdata",
        "name": "NASA Earthdata",
        "organization": "National Aeronautics and Space Administration",
        "description": "Official Earth science metadata, imagery, and visualization services.",
        "homepage_url": "https://www.earthdata.nasa.gov/",
        "documentation_url": "https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api",
        "license_name": "United States Government public data; dataset-specific terms apply",
        "license_url": "https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-information-policy",
        "attribution": "NASA EOSDIS",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_gibs",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use standards-compliant access and cache capabilities metadata.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "usgs",
        "name": "USGS Earthquake Hazards Program",
        "organization": "United States Geological Survey",
        "description": "Official earthquake catalog, feeds, and geospatial event data.",
        "homepage_url": "https://earthquake.usgs.gov/",
        "documentation_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
        "license_name": "United States Government public data; source attribution requested",
        "license_url": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
        "attribution": "U.S. Geological Survey",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use summary feeds for frequent polling and catalog queries for bounded searches.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "world-bank",
        "name": "World Bank Indicators API",
        "organization": "World Bank Group",
        "description": "Official development indicators, country metadata, and time-series observations.",
        "homepage_url": "https://data.worldbank.org/",
        "documentation_url": "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information",
        "license_name": "World Bank data terms; dataset-specific terms apply",
        "license_url": "https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets",
        "attribution": "World Bank",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use pagination and local caching for repeated indicator requests.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },
    {
        "id": "fred",
        "name": "Federal Reserve Economic Data",
        "organization": "Federal Reserve Bank of St. Louis",
        "description": "Official and aggregated economic time series with release and vintage metadata.",
        "homepage_url": "https://fred.stlouisfed.org/",
        "documentation_url": "https://fred.stlouisfed.org/docs/api/fred/",
        "license_name": "FRED terms and underlying series-provider terms",
        "license_url": "https://fred.stlouisfed.org/legal/",
        "attribution": "Federal Reserve Bank of St. Louis and the named series source",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "free_registration",
        "commercial_use_status": "series_specific_review_required",
        "redistribution_status": "series_specific_review_required",
        "automated_access_status": "allowed_with_api_key",
        "rate_limit_summary": "A free registered API key is required; preserve each series source and notes.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "un-statistics",
        "name": "United Nations Statistics Division SDG API",
        "organization": "United Nations Statistics Division",
        "description": "Official Sustainable Development Goal catalog, series, observations, and metadata.",
        "homepage_url": "https://unstats.un.org/sdgs/",
        "documentation_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/swagger/index.html",
        "license_name": "United Nations data terms; dataset and agency terms apply",
        "license_url": "https://www.un.org/en/about-us/terms-of-use",
        "attribution": "United Nations Statistics Division and reporting custodian agencies",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_catalog",
        "commercial_use_status": "review_required_by_dataset",
        "redistribution_status": "review_required_by_dataset",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded catalog and extraction requests and preserve agency metadata.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },

    {
        "id": "un-digital-library", "name": "United Nations Digital Library", "organization": "United Nations Dag Hammarskjöld Library",
        "description": "Official UN documents, resolutions, voting records, speeches, and bibliographic metadata.",
        "homepage_url": "https://digitallibrary.un.org/", "documentation_url": "https://digitallibrary.un.org/help/search-engine-api",
        "license_name": "United Nations terms; record and document-specific rights apply", "license_url": "https://www.un.org/en/about-us/terms-of-use",
        "attribution": "United Nations Digital Library", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none",
        "commercial_use_status": "metadata_allowed_document_specific_review", "redistribution_status": "metadata_allowed_document_specific_review",
        "automated_access_status": "allowed_via_documented_search_api", "rate_limit_summary": "Use bounded result groups and cache metadata.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "international_law"},
    },
    {
        "id": "ohchr", "name": "OHCHR Universal Human Rights Index", "organization": "Office of the United Nations High Commissioner for Human Rights",
        "description": "Country-specific observations and recommendations from treaty bodies, Special Procedures, and the Universal Periodic Review.",
        "homepage_url": "https://uhri.ohchr.org/", "documentation_url": "https://uhri.ohchr.org/en/our-data-api",
        "license_name": "OHCHR public data terms", "license_url": "https://uhri.ohchr.org/en/our-data-api", "attribution": "OHCHR Universal Human Rights Index",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_endpoint_documentation_by_request",
        "commercial_use_status": "allowed_with_attribution", "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed_after_endpoint_registration",
        "rate_limit_summary": "API endpoint documentation is supplied by OHCHR on request.", "review_status": "APPROVED_WITH_ATTRIBUTION", "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "updated": "daily", "domain": "human_rights"},
    },
    {
        "id": "ocha-reliefweb", "name": "OCHA ReliefWeb", "organization": "United Nations Office for the Coordination of Humanitarian Affairs",
        "description": "Curated humanitarian reports, disasters, countries, and source metadata.", "homepage_url": "https://reliefweb.int/", "documentation_url": "https://apidoc.reliefweb.int/",
        "license_name": "ReliefWeb API terms; original report rights apply", "license_url": "https://apidoc.reliefweb.int/", "attribution": "OCHA ReliefWeb and the original information partner",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_preapproved_appname", "commercial_use_status": "metadata_allowed_source_rights_apply",
        "redistribution_status": "source_rights_apply", "automated_access_status": "allowed_with_preapproved_appname", "rate_limit_summary": "Maximum 1000 results per call and 1000 calls per day.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "humanitarian"},
    },
    {
        "id": "ocha-hdx-hapi", "name": "HDX Humanitarian API", "organization": "OCHA Centre for Humanitarian Data",
        "description": "Standardized humanitarian indicators from public HDX datasets.", "homepage_url": "https://data.humdata.org/hapi", "documentation_url": "https://hdx-hapi.readthedocs.io/",
        "license_name": "HDX HAPI terms and underlying dataset licenses", "license_url": "https://hdx-hapi.readthedocs.io/", "attribution": "HDX HAPI and the named data provider",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "app_identifier_only", "commercial_use_status": "dataset_specific_review_required",
        "redistribution_status": "dataset_specific_review_required", "automated_access_status": "allowed", "rate_limit_summary": "Use an identifying app_identifier and bounded pagination.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "beta": True, "domain": "humanitarian"},
    },
    {
        "id": "un-population", "name": "UN Population Division Data Portal", "organization": "United Nations Population Division",
        "description": "Official demographic estimates, projections, fertility, mortality, migration, and related indicators.", "homepage_url": "https://population.un.org/dataportal/", "documentation_url": "https://population.un.org/dataportalapi/index.html",
        "license_name": "United Nations data terms", "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations Population Division",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_or_free_bearer_if_required", "commercial_use_status": "review_required_by_dataset",
        "redistribution_status": "review_required_by_dataset", "automated_access_status": "allowed", "rate_limit_summary": "Use bounded indicator, location, and year ranges.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "demographics"},
    },
    {
        "id": "un-comtrade", "name": "UN Comtrade", "organization": "United Nations Statistics Division",
        "description": "Official international merchandise and services trade statistics.", "homepage_url": "https://comtradeplus.un.org/", "documentation_url": "https://comtradeapi.un.org/",
        "license_name": "UN Comtrade terms", "license_url": "https://comtradeplus.un.org/", "attribution": "United Nations Comtrade Database",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_preview", "commercial_use_status": "review_required",
        "redistribution_status": "review_required", "automated_access_status": "allowed_with_public_limits", "rate_limit_summary": "Public preview endpoints are bounded; preserve reporter metadata.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "economics"},
    },
    {
        "id": "unhcr", "name": "UNHCR Refugee Statistics", "organization": "United Nations High Commissioner for Refugees",
        "description": "Official statistics on refugees, asylum-seekers, internally displaced persons, stateless persons, and solutions.", "homepage_url": "https://www.unhcr.org/refugee-statistics/", "documentation_url": "https://api.unhcr.org/docs/refugee-statistics.html",
        "license_name": "UNHCR data terms", "license_url": "https://www.unhcr.org/terms-and-conditions-use", "attribution": "UNHCR",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none", "commercial_use_status": "allowed_with_attribution",
        "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed", "rate_limit_summary": "Use pagination and country/year filters.",
        "review_status": "APPROVED_WITH_ATTRIBUTION", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "humanitarian"},
    },
    {
        "id": "un-treaty-collection", "name": "United Nations Treaty Collection", "organization": "United Nations Office of Legal Affairs",
        "description": "Treaty texts, status, signatures, ratifications, accessions, reservations, declarations, objections, and depositary notifications.",
        "homepage_url": "https://treaties.un.org/", "documentation_url": "https://treaties.un.org/", "license_name": "United Nations terms; document-specific rights apply",
        "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations Treaty Collection", "access_cost": "free", "credit_card_required": False,
        "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review", "redistribution_status": "link_or_metadata_only",
        "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public REST API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
    {
        "id": "icj", "name": "International Court of Justice", "organization": "International Court of Justice",
        "description": "Contentious cases, advisory proceedings, judgments, advisory opinions, orders, pleadings, and hearing records.", "homepage_url": "https://www.icj-cij.org/", "documentation_url": "https://www.icj-cij.org/cases",
        "license_name": "ICJ website terms and document-specific rights", "license_url": "https://www.icj-cij.org/", "attribution": "International Court of Justice",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review",
        "redistribution_status": "link_or_metadata_only", "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
    {
        "id": "un-ilc", "name": "International Law Commission", "organization": "United Nations Office of Legal Affairs",
        "description": "Draft articles, conclusions, principles, annual reports, analytical guides, and state comments on codification topics.", "homepage_url": "https://legal.un.org/ilc/", "documentation_url": "https://legal.un.org/ilc/",
        "license_name": "United Nations terms and document-specific rights", "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations International Law Commission",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review",
        "redistribution_status": "link_or_metadata_only", "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
    {
        "id": "nasa-open-apis", "name": "NASA Open APIs", "organization": "National Aeronautics and Space Administration",
        "description": "Public NASA imagery and mission APIs, including APOD and space-event services.",
        "homepage_url": "https://api.nasa.gov/", "documentation_url": "https://api.nasa.gov/",
        "license_name": "United States Government public data; endpoint-specific terms apply", "license_url": "https://www.nasa.gov/nasa-brand-center/images-and-media/",
        "attribution": "NASA", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_key_or_demo_key",
        "commercial_use_status": "allowed_subject_to_media_guidelines", "redistribution_status": "allowed_subject_to_media_guidelines",
        "automated_access_status": "allowed_with_api_key", "rate_limit_summary": "DEMO_KEY has low limits; a free registered key provides higher limits.",
        "review_status": "APPROVED_WITH_ATTRIBUTION", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "space_science"},
    },
    {
        "id": "noaa-ncei", "name": "NOAA National Centers for Environmental Information", "organization": "National Oceanic and Atmospheric Administration",
        "description": "Global climate, weather, oceanographic, coastal, and geophysical dataset discovery and access.",
        "homepage_url": "https://www.ncei.noaa.gov/", "documentation_url": "https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation",
        "license_name": "United States Government public data; dataset-specific notices apply", "license_url": "https://www.noaa.gov/disclaimer",
        "attribution": "NOAA National Centers for Environmental Information", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_access_service",
        "commercial_use_status": "allowed", "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded spatial and temporal requests and cache dataset metadata.", "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "earth_science"},
    },
    {
        "id": "ecmwf", "name": "ECMWF Open Data", "organization": "European Centre for Medium-Range Weather Forecasts",
        "description": "Open forecast products and machine-readable GRIB index files from the ECMWF real-time catalogue.",
        "homepage_url": "https://data.ecmwf.int/", "documentation_url": "https://www.ecmwf.int/en/forecasts/datasets/open-data",
        "license_name": "Creative Commons Attribution 4.0", "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "attribution": "ECMWF", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none",
        "commercial_use_status": "allowed_with_attribution", "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed",
        "rate_limit_summary": "Retrieve only required index and forecast files; cache immutable runs.", "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "atmospheric_science"},
    },
    {
        "id": "usgs-water", "name": "USGS Water Data APIs", "organization": "United States Geological Survey",
        "description": "Machine-readable streamflow, groundwater, site, and daily hydrologic observations.",
        "homepage_url": "https://api.waterdata.usgs.gov/", "documentation_url": "https://waterservices.usgs.gov/",
        "license_name": "United States Government public data; source attribution requested", "license_url": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
        "attribution": "U.S. Geological Survey", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none",
        "commercial_use_status": "allowed", "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded site, parameter, and date requests; recent readings may be provisional.", "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "hydrology"},
    },
    {
        "id": "ncbi", "name": "NCBI Entrez Programming Utilities", "organization": "National Center for Biotechnology Information",
        "description": "Stable programmatic access to biomedical literature, genes, proteins, sequences, taxonomy, and related databases.",
        "homepage_url": "https://www.ncbi.nlm.nih.gov/", "documentation_url": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        "license_name": "NCBI data and database-specific terms", "license_url": "https://www.ncbi.nlm.nih.gov/home/about/policies/",
        "attribution": "National Center for Biotechnology Information", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "optional_free_key",
        "commercial_use_status": "dataset_specific_review_required", "redistribution_status": "dataset_specific_review_required", "automated_access_status": "allowed_with_rate_limits",
        "rate_limit_summary": "Identify the tool and email; optional free key increases request allowance.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "biomedical_science"},
    },
    {
        "id": "pubchem", "name": "PubChem", "organization": "National Center for Biotechnology Information",
        "description": "Chemical compounds, structures, identifiers, properties, bioassays, and annotations through PUG REST.",
        "homepage_url": "https://pubchem.ncbi.nlm.nih.gov/", "documentation_url": "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
        "license_name": "United States Government public database; contributing-source terms may apply", "license_url": "https://pubchem.ncbi.nlm.nih.gov/docs/programmatic-access",
        "attribution": "PubChem, National Library of Medicine", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none",
        "commercial_use_status": "allowed_subject_to_contributor_terms", "redistribution_status": "allowed_subject_to_contributor_terms", "automated_access_status": "allowed_with_throttling",
        "rate_limit_summary": "PUG REST is intended for short bounded requests; use bulk services for large retrievals.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "chemistry"},
    },
    {
        "id": "gbif", "name": "Global Biodiversity Information Facility", "organization": "GBIF Secretariat",
        "description": "Species taxonomy, biodiversity occurrences, datasets, organizations, maps, and literature.",
        "homepage_url": "https://www.gbif.org/", "documentation_url": "https://techdocs.gbif.org/en/openapi/",
        "license_name": "Record and dataset-specific Creative Commons licenses", "license_url": "https://www.gbif.org/terms",
        "attribution": "GBIF and the cited publishing dataset", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_search",
        "commercial_use_status": "record_license_controls", "redistribution_status": "record_license_controls", "automated_access_status": "allowed",
        "rate_limit_summary": "Use paged occurrence search for bounded discovery and preserve each record license and dataset citation.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "biodiversity"},
    },
    {
        "id": "materials-project", "name": "Materials Project", "organization": "Lawrence Berkeley National Laboratory",
        "description": "Computed material structures, thermodynamics, electronic properties, batteries, and related materials data.",
        "homepage_url": "https://next-gen.materialsproject.org/", "documentation_url": "https://docs.materialsproject.org/downloading-data/using-the-api/getting-started",
        "license_name": "Materials Project terms and dataset citation requirements", "license_url": "https://next-gen.materialsproject.org/about/terms",
        "attribution": "Materials Project", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_registration",
        "commercial_use_status": "review_required", "redistribution_status": "review_required", "automated_access_status": "allowed_with_api_key",
        "rate_limit_summary": "A free account and API key are required; query only needed fields and preserve database version.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "materials_science"},
    },
    {
        "id": "mast", "name": "Mikulski Archive for Space Telescopes", "organization": "Space Telescope Science Institute",
        "description": "Observation metadata and data products for JWST, Hubble, TESS, Kepler, GALEX, and other missions.",
        "homepage_url": "https://archive.stsci.edu/", "documentation_url": "https://archive.stsci.edu/vo/mast_services.html",
        "license_name": "Mission and product-specific archive terms", "license_url": "https://archive.stsci.edu/disclaimer.html",
        "attribution": "MAST, Space Telescope Science Institute", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_data",
        "commercial_use_status": "allowed_subject_to_product_terms", "redistribution_status": "allowed_subject_to_product_terms", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded Portal API requests and retrieve only public products.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "astronomy"},
    },
    {
        "id": "heasarc", "name": "NASA HEASARC", "organization": "NASA Goddard Space Flight Center",
        "description": "High-energy astrophysics catalogs, observation logs, images, spectra, and mission products.",
        "homepage_url": "https://heasarc.gsfc.nasa.gov/", "documentation_url": "https://heasarc.gsfc.nasa.gov/docs/archive/apis.html",
        "license_name": "United States Government and mission-specific data terms", "license_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/disclaimer.html",
        "attribution": "NASA HEASARC and the cited mission", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_catalogs",
        "commercial_use_status": "allowed_subject_to_mission_terms", "redistribution_status": "allowed_subject_to_mission_terms", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded Xamin or VO queries and retain mission provenance.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "high_energy_astrophysics"},
    },
    {
        "id": "irsa", "name": "NASA/IPAC Infrared Science Archive", "organization": "California Institute of Technology / NASA",
        "description": "Infrared and submillimeter catalogs, images, time-series, and mission holdings through VO services.",
        "homepage_url": "https://irsa.ipac.caltech.edu/", "documentation_url": "https://irsa.ipac.caltech.edu/docs/program_interface/TAP.html",
        "license_name": "NASA and mission-specific archive terms", "license_url": "https://irsa.ipac.caltech.edu/docs/acknowledgments.html",
        "attribution": "NASA/IPAC Infrared Science Archive and the cited mission", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_data",
        "commercial_use_status": "allowed_subject_to_product_terms", "redistribution_status": "allowed_subject_to_product_terms", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded TAP/ADQL or SIA queries and prefer asynchronous services for large jobs.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "infrared_astronomy"},
    },
    {
        "id": "eso", "name": "ESO Science Archive", "organization": "European Southern Observatory",
        "description": "Public telescope observation metadata, processed products, spectra, images, and catalogs through VO standards.",
        "homepage_url": "https://archive.eso.org/", "documentation_url": "https://archive.eso.org/programmatic/",
        "license_name": "ESO data access and attribution conditions", "license_url": "https://archive.eso.org/cms/eso-data-access-policy.html",
        "attribution": "European Southern Observatory and the cited observing programme", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_data",
        "commercial_use_status": "allowed_subject_to_archive_terms", "redistribution_status": "allowed_subject_to_archive_terms", "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded TAP/ADQL queries; proprietary records remain access controlled.", "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "astronomy"},
    },

    {
        "id":"imf","name":"International Monetary Fund Data","organization":"International Monetary Fund","description":"Official macroeconomic, financial, fiscal, balance-of-payments, exchange-rate, and international statistics through SDMX APIs.","homepage_url":"https://data.imf.org/","documentation_url":"https://data.imf.org/en/Resource-Pages/IMF-API","license_name":"IMF data terms and dataset-specific conditions","license_url":"https://www.imf.org/external/terms.htm","attribution":"International Monetary Fund","access_cost":"free","credit_card_required":False,"api_key_requirement":"free_beta_portal_account_for_current_api","commercial_use_status":"dataset_specific_review_required","redistribution_status":"dataset_specific_review_required","automated_access_status":"allowed_after_free_portal_configuration","rate_limit_summary":"Use bounded SDMX queries and preserve dataset metadata.","review_status":"APPROVED_METADATA_ONLY","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"economics"},
    },
    {
        "id":"oecd","name":"OECD Data Explorer","organization":"Organisation for Economic Co-operation and Development","description":"Official economic, social, environmental, education, tax, trade, and development statistics through free SDMX APIs.","homepage_url":"https://data-explorer.oecd.org/","documentation_url":"https://www.oecd.org/en/data/insights/data-explainers/2024/09/api.html","license_name":"OECD Terms and Conditions","license_url":"https://www.oecd.org/en/about/terms-conditions.html","attribution":"OECD","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_subject_to_terms","redistribution_status":"allowed_subject_to_terms","automated_access_status":"allowed_with_rate_limits","rate_limit_summary":"Use dataset and time filters; OECD applies traffic rate limits.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"economics"},
    },
    {
        "id":"eurostat","name":"Eurostat","organization":"European Commission","description":"Official European Union statistics through JSON-stat and SDMX web services.","homepage_url":"https://ec.europa.eu/eurostat/","documentation_url":"https://ec.europa.eu/eurostat/web/user-guides/data-browser/api-data-access","license_name":"Eurostat reuse policy","license_url":"https://ec.europa.eu/eurostat/about-us/policies/copyright","attribution":"Eurostat","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_with_attribution","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed","rate_limit_summary":"Use bounded dataset filters; the database exposes current values rather than full vintages.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"economics"},
    },
    {
        "id":"ecb","name":"ECB Data Portal","organization":"European Central Bank","description":"Official monetary, banking, payments, exchange-rate, securities, and financial statistics through SDMX.","homepage_url":"https://data.ecb.europa.eu/","documentation_url":"https://data.ecb.europa.eu/help/api/overview","license_name":"ECB copyright and data reuse terms","license_url":"https://www.ecb.europa.eu/services/copyright/html/index.en.html","attribution":"European Central Bank","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_with_attribution","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed","rate_limit_summary":"Use filtered SDMX data and metadata queries.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"finance"},
    },
    {
        "id":"bis","name":"BIS Statistics","organization":"Bank for International Settlements","description":"International banking, global liquidity, credit, debt securities, property prices, and central-bank statistics through SDMX.","homepage_url":"https://stats.bis.org/","documentation_url":"https://stats.bis.org/api-doc/v2/","license_name":"BIS terms and conditions","license_url":"https://www.bis.org/terms_conditions.htm","attribution":"Bank for International Settlements","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_subject_to_terms","redistribution_status":"allowed_subject_to_terms","automated_access_status":"allowed","rate_limit_summary":"Use bounded SDMX queries and cache metadata.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"finance"},
    },
    {
        "id":"bea","name":"Bureau of Economic Analysis","organization":"U.S. Bureau of Economic Analysis","description":"Official GDP, income, spending, industry, regional, and international economic accounts.","homepage_url":"https://www.bea.gov/","documentation_url":"https://apps.bea.gov/api/signup/","license_name":"United States Government public data","license_url":"https://www.bea.gov/about/policies-and-information","attribution":"U.S. Bureau of Economic Analysis","access_cost":"free","credit_card_required":False,"api_key_requirement":"free_registration","commercial_use_status":"allowed","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed_with_api_key","rate_limit_summary":"A free UserID is required; request bounded datasets and tables.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"economics"},
    },
    {
        "id":"bls","name":"Bureau of Labor Statistics Public Data API","organization":"U.S. Bureau of Labor Statistics","description":"Official employment, unemployment, wages, prices, productivity, occupations, and workplace statistics.","homepage_url":"https://www.bls.gov/","documentation_url":"https://www.bls.gov/developers/home.htm","license_name":"United States Government public data","license_url":"https://www.bls.gov/bls/linksite.htm","attribution":"U.S. Bureau of Labor Statistics","access_cost":"free","credit_card_required":False,"api_key_requirement":"none_or_optional_free_registration","commercial_use_status":"allowed","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed_with_limits","rate_limit_summary":"Unregistered access is available; free registration raises limits.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"labour"},
    },
    {
        "id":"census","name":"U.S. Census Bureau Data API","organization":"U.S. Census Bureau","description":"Official demographic, housing, population, business, trade, and economic statistics linked to Census geographies.","homepage_url":"https://www.census.gov/data/developers.html","documentation_url":"https://www.census.gov/data/developers/guidance/api-user-guide.html","license_name":"United States Government public data","license_url":"https://www.census.gov/about/policies/copyright.html","attribution":"U.S. Census Bureau","access_cost":"free","credit_card_required":False,"api_key_requirement":"optional_free_key","commercial_use_status":"allowed","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed","rate_limit_summary":"Use dataset, vintage, variables, and geography filters; a free key supports higher use.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"demographics"},
    },
    {
        "id":"sec-edgar","name":"SEC EDGAR Data APIs","organization":"U.S. Securities and Exchange Commission","description":"Official company submissions and structured XBRL company facts from EDGAR.","homepage_url":"https://data.sec.gov/","documentation_url":"https://www.sec.gov/search-filings/edgar-application-programming-interfaces","license_name":"United States Government public records; filing content rights may vary","license_url":"https://www.sec.gov/about/privacy-information","attribution":"U.S. Securities and Exchange Commission","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_subject_to_fair_access","redistribution_status":"filing_specific_review_required","automated_access_status":"allowed_with_identifying_user_agent","rate_limit_summary":"Comply with SEC Fair Access and identify the application and contact.","review_status":"APPROVED_METADATA_ONLY","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"company_finance"},
    },
    {
        "id":"eia","name":"U.S. Energy Information Administration Open Data","organization":"U.S. Energy Information Administration","description":"Official energy production, consumption, prices, capacity, forecasts, and emissions statistics through API v2.","homepage_url":"https://www.eia.gov/opendata/","documentation_url":"https://www.eia.gov/opendata/documentation.php","license_name":"United States Government public data and EIA API terms","license_url":"https://www.eia.gov/opendata/register.php","attribution":"U.S. Energy Information Administration","access_cost":"free","credit_card_required":False,"api_key_requirement":"free_registration","commercial_use_status":"allowed_with_attribution","redistribution_status":"allowed_with_attribution","automated_access_status":"allowed_with_api_key","rate_limit_summary":"A free API key is required; use API v2 routes and bounded result lengths.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"energy"},
    },
    {
        "id":"faostat","name":"FAOSTAT","organization":"Food and Agriculture Organization of the United Nations","description":"Official global food, agriculture, forestry, fisheries, trade, prices, land, and emissions statistics.","homepage_url":"https://www.fao.org/faostat/","documentation_url":"https://www.fao.org/statistics/highlights-archive/highlights-detail/faostat-launches-a-new-api-developer-portal-to-make-data-access-easier/en","license_name":"FAOSTAT terms and dataset-specific conditions","license_url":"https://www.fao.org/contact-us/terms/en/","attribution":"Food and Agriculture Organization of the United Nations","access_cost":"free","credit_card_required":False,"api_key_requirement":"none_or_free_portal_configuration","commercial_use_status":"allowed_subject_to_dataset_terms","redistribution_status":"allowed_subject_to_dataset_terms","automated_access_status":"allowed","rate_limit_summary":"Use domain, area, item, element, and year filters.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"agriculture"},
    },
    {
        "id":"ilostat","name":"ILOSTAT","organization":"International Labour Organization","description":"Official internationally comparable labour statistics through SDMX and bulk data services.","homepage_url":"https://ilostat.ilo.org/","documentation_url":"https://ilostat.ilo.org/resources/sdmx-tools/","license_name":"ILOSTAT copyright and permissions terms","license_url":"https://www.ilo.org/about-ilo/legal-and-privacy-information/copyright-and-permissions","attribution":"International Labour Organization","access_cost":"free","credit_card_required":False,"api_key_requirement":"none","commercial_use_status":"allowed_subject_to_terms","redistribution_status":"allowed_subject_to_terms","automated_access_status":"allowed","rate_limit_summary":"Use bounded SDMX queries or bulk files and preserve indicator definitions.","review_status":"APPROVED_WITH_ATTRIBUTION","last_reviewed_at":REVIEWED_AT,"metadata":{"official":True,"domain":"labour"},
    },
]

DEFAULT_LIVE_DATA_CONNECTORS: list[dict] = [
    {
        "id": "met-no.locationforecast",
        "source_id": "met-norway",
        "name": "MET Norway Global Location Forecast",
        "domain": "weather",
        "description": "Coordinate-based nine-day weather forecast normalized into metric observations.",
        "adapter": "met_locationforecast_v2",
        "base_url": "https://api.met.no/weatherapi/locationforecast/2.0/compact",
        "refresh_policy": "PT1H",
        "freshness_window_seconds": 10800,
        "capabilities": ["forecast", "point_geometry", "timeseries", "global"],
        "configuration": {"required_parameters": ["lat", "lon"]},
    },
    {
        "id": "nasa.gibs-wmts",
        "source_id": "nasa-earthdata",
        "name": "NASA GIBS WMTS Layer Registry",
        "domain": "earth_observation",
        "description": "NASA GIBS capabilities catalog normalized into discoverable map-layer records.",
        "adapter": "nasa_gibs_wmts_v1",
        "base_url": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 172800,
        "max_response_bytes": 12582912,
        "capabilities": ["wmts", "map_layers", "satellite_imagery", "global"],
        "configuration": {"projection": "EPSG:4326"},
    },
    {
        "id": "usgs.earthquakes",
        "source_id": "usgs",
        "name": "USGS Earthquake Summary Feed",
        "domain": "hazards",
        "description": "Near-real-time earthquake events from official USGS GeoJSON summary feeds.",
        "adapter": "usgs_earthquakes_geojson_v1",
        "base_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary",
        "refresh_policy": "PT5M",
        "freshness_window_seconds": 3600,
        "capabilities": ["events", "geojson", "near_real_time", "global"],
        "configuration": {"default_feed": "all_hour", "allowed_feeds": ["all_hour", "all_day", "2.5_day", "4.5_week", "significant_month"]},
    },
    {
        "id": "world-bank.indicators",
        "source_id": "world-bank",
        "name": "World Bank Development Indicators",
        "domain": "economics",
        "description": "Country and aggregate indicator observations through the World Bank V2 API.",
        "adapter": "world_bank_indicators_v2",
        "base_url": "https://api.worldbank.org/v2",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "countries", "development", "sustainability"],
        "configuration": {"required_parameters": ["indicator"], "default_country": "all"},
    },
    {
        "id": "fred.series-observations",
        "source_id": "fred",
        "name": "FRED Series Observations",
        "domain": "economics",
        "description": "Economic series observations using a free registered FRED API key.",
        "adapter": "fred_series_observations_v1",
        "base_url": "https://api.stlouisfed.org/fred/series/observations",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "vintages", "economic_releases"],
        "configuration": {"required_parameters": ["series_id"], "credential_env": "SC_CORE_FRED_API_KEY", "public_records": False},
    },
    {
        "id": "un.sdg-catalog",
        "source_id": "un-statistics",
        "name": "UN SDG Goal and Series Catalog",
        "domain": "sustainability",
        "description": "Official SDG goal and indicator-series catalog discovery.",
        "adapter": "un_sdg_catalog_v1",
        "base_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/v1/sdg",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 604800,
        "capabilities": ["sdg_goals", "indicator_series", "official_metadata", "global"],
        "configuration": {"default_resource": "goals", "allowed_resources": ["goals", "series"]},
    },

    {
        "id": "un.digital-library", "source_id": "un-digital-library", "name": "UN Digital Library Official Document Search", "domain": "international_law",
        "description": "Searches official UN document metadata and classifies resolution and document authority.", "adapter": "un_digital_library_search_v1",
        "base_url": "https://digitallibrary.un.org/search", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["official_documents", "resolutions", "voting_records", "speeches", "legal_authority", "search"],
        "configuration": {"required_parameters": ["query"], "default_fields": "recid,title,document_symbol,publication_date,creation_date,language,subjects,collections,urls"},
    },
    {
        "id": "un.sdg-metadata", "source_id": "un-statistics", "name": "UN SDG Metadata Reports", "domain": "sustainability",
        "description": "Retrieves official SDG methodology reports by series and reference area.", "adapter": "un_sdg_metadata_v1",
        "base_url": "https://unstats.un.org/SDGMetadataAPI/api/Metadata", "refresh_policy": "P7D", "freshness_window_seconds": 2592000,
        "capabilities": ["sdg_metadata", "methodology", "sdmx_report"], "configuration": {"required_parameters": ["series"]},
    },
    {
        "id": "ocha.reliefweb-reports", "source_id": "ocha-reliefweb", "name": "OCHA ReliefWeb Reports", "domain": "humanitarian",
        "description": "Curated humanitarian reports with countries, sources, themes, and publication dates.", "adapter": "reliefweb_reports_v2",
        "base_url": "https://api.reliefweb.int/v2/reports", "refresh_policy": "PT1H", "freshness_window_seconds": 86400,
        "capabilities": ["reports", "disasters", "countries", "humanitarian_events", "search"],
        "configuration": {"credential_env": "SC_CORE_RELIEFWEB_APPNAME", "public_records": True},
    },
    {
        "id": "ocha.hdx-hapi", "source_id": "ocha-hdx-hapi", "name": "HDX Humanitarian Indicators", "domain": "humanitarian",
        "description": "Standardized humanitarian indicators through HDX HAPI v2.", "adapter": "hdx_hapi_v2",
        "base_url": "https://hapi.humdata.org/api/v2", "refresh_policy": "P1D", "freshness_window_seconds": 604800,
        "capabilities": ["humanitarian_indicators", "population", "needs", "funding", "food_security", "operational_presence"],
        "configuration": {"default_resource": "affected-people/refugees-persons-of-concern", "allowed_resources": ["affected-people/refugees-persons-of-concern", "affected-people/idps", "affected-people/humanitarian-needs", "coordination-context/operational-presence", "coordination-context/funding", "food-security-nutrition-poverty/food-security", "geography-infrastructure/baseline-population", "climate/hazards-rainfall"]},
    },
    {
        "id": "un.population-data", "source_id": "un-population", "name": "UN Population Data Portal", "domain": "demographics",
        "description": "Official demographic indicator observations by location and year range.", "adapter": "un_population_data_v1",
        "base_url": "https://population.un.org/dataportalapi/api/v1", "refresh_policy": "P30D", "freshness_window_seconds": 31536000,
        "capabilities": ["population", "fertility", "mortality", "migration", "projections", "timeseries"],
        "configuration": {"required_parameters": ["indicators", "locations", "start_year", "end_year"], "optional_bearer_env": "SC_CORE_UN_POPULATION_BEARER_TOKEN"},
    },
    {
        "id": "un.comtrade", "source_id": "un-comtrade", "name": "UN Comtrade Public Trade Data", "domain": "economics",
        "description": "Public-preview international trade flows by reporter, period, partner, commodity, and flow.", "adapter": "un_comtrade_public_v1",
        "base_url": "https://comtradeapi.un.org/public/v1/preview/C/A/HS", "refresh_policy": "P1D", "freshness_window_seconds": 2592000,
        "capabilities": ["trade", "imports", "exports", "commodities", "partners", "timeseries"],
        "configuration": {"required_parameters": ["reporter_code", "period"], "public_preview_limit": 500},
    },
    {
        "id": "unhcr.population", "source_id": "unhcr", "name": "UNHCR Refugee Population Statistics", "domain": "humanitarian",
        "description": "Official annual statistics on displaced and stateless populations.", "adapter": "unhcr_population_v1",
        "base_url": "https://api.unhcr.org/population/v1/population/", "refresh_policy": "P30D", "freshness_window_seconds": 31536000,
        "capabilities": ["refugees", "asylum_seekers", "idps", "statelessness", "solutions", "demographics"],
        "configuration": {"optional_parameters": ["coo", "coa", "year_from", "year_to"]},
    },
    {
        "id": "ohchr.uhri-recommendations", "source_id": "ohchr", "name": "OHCHR Universal Human Rights Index", "domain": "international_law",
        "description": "Country-specific human-rights recommendations with themes, mechanisms, and SDG links.", "adapter": "ohchr_uhri_v1",
        "base_url": "https://uhri.ohchr.org/", "refresh_policy": "P1D", "freshness_window_seconds": 604800,
        "capabilities": ["human_rights_recommendations", "treaty_bodies", "special_procedures", "upr", "sdg_links"],
        "configuration": {"credential_env": "SC_CORE_UHRI_API_URL", "registration_url": "https://uhri.ohchr.org/en/our-data-api"},
    },

    {
        "id": "nasa.cmr-collections", "source_id": "nasa-earthdata", "name": "NASA CMR Collection Discovery", "domain": "earth_science",
        "description": "Searches NASA Earth science collection metadata by keyword, concept, time, and spatial extent.", "adapter": "nasa_cmr_collections_v1",
        "base_url": "https://cmr.earthdata.nasa.gov/search/collections.json", "refresh_policy": "P1D", "freshness_window_seconds": 604800,
        "capabilities": ["dataset_discovery", "earth_observation", "spatial", "temporal", "doi", "science_keywords"],
        "configuration": {"required_parameters": ["keyword"], "default_page_size": 50},
    },
    {
        "id": "nasa.apod", "source_id": "nasa-open-apis", "name": "NASA Astronomy Picture of the Day", "domain": "space_science",
        "description": "Public NASA astronomy imagery metadata with explanation, media type, and copyright context.", "adapter": "nasa_apod_v1",
        "base_url": "https://api.nasa.gov/planetary/apod", "refresh_policy": "P1D", "freshness_window_seconds": 172800,
        "capabilities": ["astronomy_image", "public_education", "daily_feed"], "configuration": {"credential_env": "SC_CORE_NASA_API_KEY"},
    },
    {
        "id": "noaa.ncei-data", "source_id": "noaa-ncei", "name": "NOAA NCEI Access Data Service", "domain": "earth_science",
        "description": "Retrieves bounded climate and environmental observations from an identified NCEI dataset.", "adapter": "noaa_ncei_data_v1",
        "base_url": "https://www.ncei.noaa.gov/access/services/data/v1", "refresh_policy": "P1D", "freshness_window_seconds": 2592000,
        "capabilities": ["climate", "weather", "ocean", "geophysical", "timeseries", "stations"],
        "configuration": {"required_parameters": ["dataset", "start_date", "end_date"], "default_limit": 1000},
    },
    {
        "id": "ecmwf.open-data-index", "source_id": "ecmwf", "name": "ECMWF Open Forecast Index", "domain": "atmospheric_science",
        "description": "Reads machine-readable index records for an explicitly selected ECMWF forecast run and GRIB file.", "adapter": "ecmwf_open_data_index_v1",
        "base_url": "https://data.ecmwf.int/forecasts", "refresh_policy": "PT6H", "freshness_window_seconds": 43200,
        "capabilities": ["forecast_catalog", "grib", "ensemble", "machine_learning_forecast", "global"],
        "configuration": {"required_parameters": ["date", "run", "stream", "type", "step"], "allowed_runs": ["00", "06", "12", "18"]},
    },
    {
        "id": "usgs.water-instantaneous", "source_id": "usgs-water", "name": "USGS Instantaneous Water Values", "domain": "hydrology",
        "description": "Recent streamflow, gage height, temperature, and other hydrologic measurements for bounded sites or regions.", "adapter": "usgs_water_iv_v1",
        "base_url": "https://waterservices.usgs.gov/nwis/iv/", "refresh_policy": "PT15M", "freshness_window_seconds": 7200,
        "capabilities": ["streamflow", "gage_height", "water_temperature", "provisional_data", "timeseries"],
        "configuration": {"required_one_of": ["sites", "state_cd", "b_box"], "default_period": "P1D"},
    },
    {
        "id": "ncbi.entrez-search", "source_id": "ncbi", "name": "NCBI Entrez Search", "domain": "biomedical_science",
        "description": "Searches an allowed Entrez database and retrieves normalized document summaries.", "adapter": "ncbi_entrez_search_v1",
        "base_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils", "refresh_policy": "manual", "freshness_window_seconds": 2592000,
        "capabilities": ["literature", "genes", "proteins", "sequences", "taxonomy", "bioproject", "biosample"],
        "configuration": {"required_parameters": ["db", "term"], "allowed_databases": ["pubmed", "pmc", "gene", "protein", "nuccore", "taxonomy", "bioproject", "biosample"], "tool": "sustainable_catalyst_core"},
    },
    {
        "id": "pubchem.compound-properties", "source_id": "pubchem", "name": "PubChem Compound Properties", "domain": "chemistry",
        "description": "Retrieves bounded compound identity, molecular formula, mass, structure, and descriptor records.", "adapter": "pubchem_compound_properties_v1",
        "base_url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound", "refresh_policy": "manual", "freshness_window_seconds": 2592000,
        "capabilities": ["compound", "structure", "properties", "identifiers", "chemistry"],
        "configuration": {"required_parameters": ["namespace", "identifier"], "allowed_namespaces": ["cid", "name", "smiles", "inchikey"]},
    },
    {
        "id": "gbif.occurrences", "source_id": "gbif", "name": "GBIF Occurrence Search", "domain": "biodiversity",
        "description": "Bounded biodiversity occurrence discovery with coordinates, taxonomy, dataset, quality flags, and record license.", "adapter": "gbif_occurrence_search_v1",
        "base_url": "https://api.gbif.org/v1/occurrence/search", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["species_occurrence", "taxonomy", "geospatial", "dataset_citation", "record_license"],
        "configuration": {"required_one_of": ["scientific_name", "taxon_key", "country", "geometry"], "max_limit": 300},
    },
    {
        "id": "materials-project.summary", "source_id": "materials-project", "name": "Materials Project Summary Search", "domain": "materials_science",
        "description": "Searches current Materials Project summary records using a free registered API key.", "adapter": "materials_project_summary_v1",
        "base_url": "https://api.materialsproject.org/materials/summary/", "refresh_policy": "manual", "freshness_window_seconds": 2592000,
        "capabilities": ["materials", "structures", "thermodynamics", "electronic_structure", "database_version"],
        "configuration": {"credential_env": "SC_CORE_MATERIALS_PROJECT_API_KEY", "required_one_of": ["material_ids", "formula", "chemsys", "elements"]},
    },
    {
        "id": "mast.observations", "source_id": "mast", "name": "MAST Telescope Observation Search", "domain": "astronomy",
        "description": "Queries public telescope observation metadata through the MAST Portal API.", "adapter": "mast_observations_v1",
        "base_url": "https://mast.stsci.edu/api/v0.1/invoke", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["jwst", "hubble", "tess", "kepler", "observations", "data_products"],
        "configuration": {"required_one_of": ["target_name", "coordinates", "collection"], "max_pagesize": 200},
    },
    {
        "id": "heasarc.xamin", "source_id": "heasarc", "name": "HEASARC Xamin Catalog Query", "domain": "astronomy",
        "description": "Queries an allowed HEASARC high-energy astronomy table with bounded result limits.", "adapter": "heasarc_xamin_v1",
        "base_url": "https://heasarc.gsfc.nasa.gov/xamin/query", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["xray", "gamma_ray", "catalogs", "observation_logs", "missions"],
        "configuration": {"required_parameters": ["table"], "default_maxrows": 100},
    },
    {
        "id": "irsa.tap", "source_id": "irsa", "name": "IRSA TAP Astronomy Query", "domain": "astronomy",
        "description": "Executes bounded read-only ADQL queries against public IRSA catalog tables.", "adapter": "ivoa_tap_json_v1",
        "base_url": "https://irsa.ipac.caltech.edu/TAP/sync", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["tap", "adql", "infrared", "catalogs", "time_domain"],
        "configuration": {"archive": "IRSA", "required_parameters": ["query"], "maxrec": 200},
    },
    {
        "id": "eso.tap", "source_id": "eso", "name": "ESO TAP Observation Query", "domain": "astronomy",
        "description": "Executes bounded read-only ADQL queries against public ESO observation metadata.", "adapter": "ivoa_tap_json_v1",
        "base_url": "https://archive.eso.org/tap_obs/sync", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["tap", "adql", "observations", "spectra", "images", "ground_telescopes"],
        "configuration": {"archive": "ESO", "required_parameters": ["query"], "maxrec": 200},
    },
    {
        "id":"imf.sdmx","source_id":"imf","name":"IMF SDMX Economic Statistics","domain":"economics","description":"Reads bounded IMF statistical observations after the current free API endpoint is configured.","adapter":"sdmx_csv_observations_v1","base_url":"https://portal.api.imf.org/","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["macroeconomics","exchange_rates","national_accounts","balance_of_payments","sdmx"],"configuration":{"endpoint_env":"SC_CORE_IMF_API_BASE_URL","provider":"IMF","path_style":"agency_dataset","format":"csvfile","record_type":"macroeconomic_indicator","subject":"macroeconomics","required_parameters":["agency","dataset","key"]},
    },
    {
        "id":"oecd.sdmx","source_id":"oecd","name":"OECD Data Explorer SDMX","domain":"economics","description":"Retrieves bounded OECD Data Explorer observations in SDMX CSV format.","adapter":"sdmx_csv_observations_v1","base_url":"https://sdmx.oecd.org/public/rest/data","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["economics","social","environment","education","trade","sdmx"],"configuration":{"provider":"OECD","path_style":"agency_dataset","format":"csvfilewithlabels","record_type":"official_statistic","subject":"economics","required_parameters":["agency","dataset","key"]},
    },
    {
        "id":"eurostat.statistics","source_id":"eurostat","name":"Eurostat Statistics API","domain":"economics","description":"Retrieves filtered Eurostat datasets in JSON-stat 2.0 format.","adapter":"eurostat_jsonstat_v1","base_url":"https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data","refresh_policy":"PT12H","freshness_window_seconds":2592000,"capabilities":["eu_statistics","json_stat","economics","population","energy","environment"],"configuration":{"required_parameters":["dataset"],"subject":"economics"},
    },
    {
        "id":"ecb.sdmx","source_id":"ecb","name":"ECB SDMX Statistics","domain":"finance","description":"Retrieves monetary, exchange-rate, banking, and financial statistics from the ECB Data Portal.","adapter":"sdmx_csv_observations_v1","base_url":"https://data-api.ecb.europa.eu/service/data","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["monetary_policy","exchange_rates","banking","payments","sdmx"],"configuration":{"provider":"ECB","path_style":"flow_key","format":"csvdata","record_type":"macroeconomic_indicator","subject":"finance","required_parameters":["flow_ref","key"]},
    },
    {
        "id":"bis.sdmx","source_id":"bis","name":"BIS SDMX Statistics","domain":"finance","description":"Retrieves bounded BIS international banking and financial observations.","adapter":"sdmx_csv_observations_v1","base_url":"https://stats.bis.org/api/v2/data","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["banking","global_liquidity","credit","debt_securities","property_prices","sdmx"],"configuration":{"provider":"BIS","path_style":"flow_key","format":"csvfile","record_type":"macroeconomic_indicator","subject":"finance","required_parameters":["flow_ref","key"]},
    },
    {
        "id":"bea.statistics","source_id":"bea","name":"BEA Economic Statistics","domain":"economics","description":"Retrieves official BEA data and metadata using a free registered UserID.","adapter":"bea_data_v1","base_url":"https://apps.bea.gov/api/data/","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["gdp","income","spending","industry","regional","international_accounts"],"configuration":{"credential_env":"SC_CORE_BEA_API_KEY","required_parameters":["dataset_name"]},
    },
    {
        "id":"bls.timeseries","source_id":"bls","name":"BLS Public Time Series","domain":"labour","description":"Retrieves bounded official BLS time series using the public version 2 API.","adapter":"bls_series_v2","base_url":"https://api.bls.gov/publicAPI/v2/timeseries/data/","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["employment","unemployment","wages","cpi","ppi","productivity"],"configuration":{"required_parameters":["series_ids"]},
    },
    {
        "id":"census.data","source_id":"census","name":"Census Data API","domain":"demographics","description":"Retrieves selected variables from a named Census dataset, vintage, and geography.","adapter":"census_data_v1","base_url":"https://api.census.gov/data","refresh_policy":"P30D","freshness_window_seconds":31536000,"capabilities":["population","housing","business","income","poverty","geography"],"configuration":{"required_parameters":["year","dataset","get","for"]},
    },
    {
        "id":"sec.companyfacts","source_id":"sec-edgar","name":"SEC EDGAR Company Facts","domain":"company_finance","description":"Retrieves structured XBRL company facts for a specified CIK under SEC fair-access rules.","adapter":"sec_companyfacts_v1","base_url":"https://data.sec.gov/api/xbrl/companyfacts","refresh_policy":"P1D","freshness_window_seconds":604800,"capabilities":["xbrl","company_facts","filings","fundamentals","edgar"],"configuration":{"required_parameters":["cik"],"default_taxonomy":"us-gaap"},
    },
    {
        "id":"eia.v2-data","source_id":"eia","name":"EIA Open Data API v2","domain":"energy","description":"Retrieves official EIA energy data from a selected API v2 route using a free key.","adapter":"eia_v2_data_v1","base_url":"https://api.eia.gov/v2","refresh_policy":"P1D","freshness_window_seconds":2592000,"capabilities":["energy","electricity","petroleum","natural_gas","prices","emissions"],"configuration":{"credential_env":"SC_CORE_EIA_API_KEY","required_parameters":["route","data_fields"]},
    },
    {
        "id":"faostat.data","source_id":"faostat","name":"FAOSTAT Data","domain":"agriculture","description":"Retrieves bounded food and agriculture observations from an official FAOSTAT data service.","adapter":"faostat_data_v1","base_url":"https://fenixservices.fao.org/faostat/api/v1/en/data","refresh_policy":"P30D","freshness_window_seconds":31536000,"capabilities":["agriculture","food","trade","prices","land","emissions"],"configuration":{"required_parameters":["domain_code"],"endpoint_env":"SC_CORE_FAOSTAT_API_BASE_URL"},
    },
    {
        "id":"ilostat.sdmx","source_id":"ilostat","name":"ILOSTAT SDMX Labour Statistics","domain":"labour","description":"Retrieves internationally comparable labour statistics through an ILOSTAT SDMX endpoint.","adapter":"sdmx_csv_observations_v1","base_url":"https://sdmx.ilo.org/rest/data","refresh_policy":"P30D","freshness_window_seconds":31536000,"capabilities":["employment","unemployment","wages","working_time","informality","sdmx"],"configuration":{"provider":"ILOSTAT","path_style":"flow_key","format":"csv","record_type":"labour_statistic","subject":"labour","required_parameters":["flow_ref","key"]},
    },

]
