from __future__ import annotations

from datetime import datetime, timezone

REVIEWED_AT = datetime(2026, 7, 14, tzinfo=timezone.utc)

DEFAULT_LIVE_DATA_SOURCES: list[dict] = [
    {
        "id": "met-norway",
        "name": "MET Norway Weather API",
        "organization": "Norwegian Meteorological Institute",
        "description": "Official global forecast data and related meteorological services.",
        "homepage_url": "https://api.met.no/",
        "documentation_url": "https://api.met.no/weatherapi/locationforecast/2.0/documentation",
        "license_name": "Creative Commons attribution terms; provider terms apply",
        "license_url": "https://api.met.no/doc/TermsOfService",
        "attribution": "Norwegian Meteorological Institute",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_with_attribution",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed_with_identifying_user_agent",
        "rate_limit_summary": "Cache responses and identify the application with a contact-bearing User-Agent.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "Norway"},
    },
    {
        "id": "nasa-earthdata",
        "name": "NASA Earthdata",
        "organization": "National Aeronautics and Space Administration",
        "description": "Official Earth science metadata, imagery, and visualization services.",
        "homepage_url": "https://www.earthdata.nasa.gov/",
        "documentation_url": "https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api",
        "license_name": "United States Government public data; dataset-specific terms apply",
        "license_url": "https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-information-policy",
        "attribution": "NASA EOSDIS",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_gibs",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use standards-compliant access and cache capabilities metadata.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "usgs",
        "name": "USGS Earthquake Hazards Program",
        "organization": "United States Geological Survey",
        "description": "Official earthquake catalog, feeds, and geospatial event data.",
        "homepage_url": "https://earthquake.usgs.gov/",
        "documentation_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
        "license_name": "United States Government public data; source attribution requested",
        "license_url": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
        "attribution": "U.S. Geological Survey",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use summary feeds for frequent polling and catalog queries for bounded searches.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "world-bank",
        "name": "World Bank Indicators API",
        "organization": "World Bank Group",
        "description": "Official development indicators, country metadata, and time-series observations.",
        "homepage_url": "https://data.worldbank.org/",
        "documentation_url": "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information",
        "license_name": "World Bank data terms; dataset-specific terms apply",
        "license_url": "https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets",
        "attribution": "World Bank",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use pagination and local caching for repeated indicator requests.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },
    {
        "id": "fred",
        "name": "Federal Reserve Economic Data",
        "organization": "Federal Reserve Bank of St. Louis",
        "description": "Official and aggregated economic time series with release and vintage metadata.",
        "homepage_url": "https://fred.stlouisfed.org/",
        "documentation_url": "https://fred.stlouisfed.org/docs/api/fred/",
        "license_name": "FRED terms and underlying series-provider terms",
        "license_url": "https://fred.stlouisfed.org/legal/",
        "attribution": "Federal Reserve Bank of St. Louis and the named series source",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "free_registration",
        "commercial_use_status": "series_specific_review_required",
        "redistribution_status": "series_specific_review_required",
        "automated_access_status": "allowed_with_api_key",
        "rate_limit_summary": "A free registered API key is required; preserve each series source and notes.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "un-statistics",
        "name": "United Nations Statistics Division SDG API",
        "organization": "United Nations Statistics Division",
        "description": "Official Sustainable Development Goal catalog, series, observations, and metadata.",
        "homepage_url": "https://unstats.un.org/sdgs/",
        "documentation_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/swagger/index.html",
        "license_name": "United Nations data terms; dataset and agency terms apply",
        "license_url": "https://www.un.org/en/about-us/terms-of-use",
        "attribution": "United Nations Statistics Division and reporting custodian agencies",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_catalog",
        "commercial_use_status": "review_required_by_dataset",
        "redistribution_status": "review_required_by_dataset",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded catalog and extraction requests and preserve agency metadata.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },

    {
        "id": "un-digital-library", "name": "United Nations Digital Library", "organization": "United Nations Dag Hammarskjöld Library",
        "description": "Official UN documents, resolutions, voting records, speeches, and bibliographic metadata.",
        "homepage_url": "https://digitallibrary.un.org/", "documentation_url": "https://digitallibrary.un.org/help/search-engine-api",
        "license_name": "United Nations terms; record and document-specific rights apply", "license_url": "https://www.un.org/en/about-us/terms-of-use",
        "attribution": "United Nations Digital Library", "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none",
        "commercial_use_status": "metadata_allowed_document_specific_review", "redistribution_status": "metadata_allowed_document_specific_review",
        "automated_access_status": "allowed_via_documented_search_api", "rate_limit_summary": "Use bounded result groups and cache metadata.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "international_law"},
    },
    {
        "id": "ohchr", "name": "OHCHR Universal Human Rights Index", "organization": "Office of the United Nations High Commissioner for Human Rights",
        "description": "Country-specific observations and recommendations from treaty bodies, Special Procedures, and the Universal Periodic Review.",
        "homepage_url": "https://uhri.ohchr.org/", "documentation_url": "https://uhri.ohchr.org/en/our-data-api",
        "license_name": "OHCHR public data terms", "license_url": "https://uhri.ohchr.org/en/our-data-api", "attribution": "OHCHR Universal Human Rights Index",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_endpoint_documentation_by_request",
        "commercial_use_status": "allowed_with_attribution", "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed_after_endpoint_registration",
        "rate_limit_summary": "API endpoint documentation is supplied by OHCHR on request.", "review_status": "APPROVED_WITH_ATTRIBUTION", "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "updated": "daily", "domain": "human_rights"},
    },
    {
        "id": "ocha-reliefweb", "name": "OCHA ReliefWeb", "organization": "United Nations Office for the Coordination of Humanitarian Affairs",
        "description": "Curated humanitarian reports, disasters, countries, and source metadata.", "homepage_url": "https://reliefweb.int/", "documentation_url": "https://apidoc.reliefweb.int/",
        "license_name": "ReliefWeb API terms; original report rights apply", "license_url": "https://apidoc.reliefweb.int/", "attribution": "OCHA ReliefWeb and the original information partner",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "free_preapproved_appname", "commercial_use_status": "metadata_allowed_source_rights_apply",
        "redistribution_status": "source_rights_apply", "automated_access_status": "allowed_with_preapproved_appname", "rate_limit_summary": "Maximum 1000 results per call and 1000 calls per day.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "humanitarian"},
    },
    {
        "id": "ocha-hdx-hapi", "name": "HDX Humanitarian API", "organization": "OCHA Centre for Humanitarian Data",
        "description": "Standardized humanitarian indicators from public HDX datasets.", "homepage_url": "https://data.humdata.org/hapi", "documentation_url": "https://hdx-hapi.readthedocs.io/",
        "license_name": "HDX HAPI terms and underlying dataset licenses", "license_url": "https://hdx-hapi.readthedocs.io/", "attribution": "HDX HAPI and the named data provider",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "app_identifier_only", "commercial_use_status": "dataset_specific_review_required",
        "redistribution_status": "dataset_specific_review_required", "automated_access_status": "allowed", "rate_limit_summary": "Use an identifying app_identifier and bounded pagination.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "beta": True, "domain": "humanitarian"},
    },
    {
        "id": "un-population", "name": "UN Population Division Data Portal", "organization": "United Nations Population Division",
        "description": "Official demographic estimates, projections, fertility, mortality, migration, and related indicators.", "homepage_url": "https://population.un.org/dataportal/", "documentation_url": "https://population.un.org/dataportalapi/index.html",
        "license_name": "United Nations data terms", "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations Population Division",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_or_free_bearer_if_required", "commercial_use_status": "review_required_by_dataset",
        "redistribution_status": "review_required_by_dataset", "automated_access_status": "allowed", "rate_limit_summary": "Use bounded indicator, location, and year ranges.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "demographics"},
    },
    {
        "id": "un-comtrade", "name": "UN Comtrade", "organization": "United Nations Statistics Division",
        "description": "Official international merchandise and services trade statistics.", "homepage_url": "https://comtradeplus.un.org/", "documentation_url": "https://comtradeapi.un.org/",
        "license_name": "UN Comtrade terms", "license_url": "https://comtradeplus.un.org/", "attribution": "United Nations Comtrade Database",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none_for_public_preview", "commercial_use_status": "review_required",
        "redistribution_status": "review_required", "automated_access_status": "allowed_with_public_limits", "rate_limit_summary": "Public preview endpoints are bounded; preserve reporter metadata.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "economics"},
    },
    {
        "id": "unhcr", "name": "UNHCR Refugee Statistics", "organization": "United Nations High Commissioner for Refugees",
        "description": "Official statistics on refugees, asylum-seekers, internally displaced persons, stateless persons, and solutions.", "homepage_url": "https://www.unhcr.org/refugee-statistics/", "documentation_url": "https://api.unhcr.org/docs/refugee-statistics.html",
        "license_name": "UNHCR data terms", "license_url": "https://www.unhcr.org/terms-and-conditions-use", "attribution": "UNHCR",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "none", "commercial_use_status": "allowed_with_attribution",
        "redistribution_status": "allowed_with_attribution", "automated_access_status": "allowed", "rate_limit_summary": "Use pagination and country/year filters.",
        "review_status": "APPROVED_WITH_ATTRIBUTION", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "domain": "humanitarian"},
    },
    {
        "id": "un-treaty-collection", "name": "United Nations Treaty Collection", "organization": "United Nations Office of Legal Affairs",
        "description": "Treaty texts, status, signatures, ratifications, accessions, reservations, declarations, objections, and depositary notifications.",
        "homepage_url": "https://treaties.un.org/", "documentation_url": "https://treaties.un.org/", "license_name": "United Nations terms; document-specific rights apply",
        "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations Treaty Collection", "access_cost": "free", "credit_card_required": False,
        "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review", "redistribution_status": "link_or_metadata_only",
        "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public REST API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
    {
        "id": "icj", "name": "International Court of Justice", "organization": "International Court of Justice",
        "description": "Contentious cases, advisory proceedings, judgments, advisory opinions, orders, pleadings, and hearing records.", "homepage_url": "https://www.icj-cij.org/", "documentation_url": "https://www.icj-cij.org/cases",
        "license_name": "ICJ website terms and document-specific rights", "license_url": "https://www.icj-cij.org/", "attribution": "International Court of Justice",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review",
        "redistribution_status": "link_or_metadata_only", "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
    {
        "id": "un-ilc", "name": "International Law Commission", "organization": "United Nations Office of Legal Affairs",
        "description": "Draft articles, conclusions, principles, annual reports, analytical guides, and state comments on codification topics.", "homepage_url": "https://legal.un.org/ilc/", "documentation_url": "https://legal.un.org/ilc/",
        "license_name": "United Nations terms and document-specific rights", "license_url": "https://www.un.org/en/about-us/terms-of-use", "attribution": "United Nations International Law Commission",
        "access_cost": "free", "credit_card_required": False, "api_key_requirement": "no_documented_public_api", "commercial_use_status": "metadata_only_review",
        "redistribution_status": "link_or_metadata_only", "automated_access_status": "controlled_document_access", "rate_limit_summary": "No general public API is documented; no automated connector is enabled.",
        "review_status": "APPROVED_METADATA_ONLY", "last_reviewed_at": REVIEWED_AT, "metadata": {"official": True, "connector_status": "deferred"},
    },
]

DEFAULT_LIVE_DATA_CONNECTORS: list[dict] = [
    {
        "id": "met-no.locationforecast",
        "source_id": "met-norway",
        "name": "MET Norway Global Location Forecast",
        "domain": "weather",
        "description": "Coordinate-based nine-day weather forecast normalized into metric observations.",
        "adapter": "met_locationforecast_v2",
        "base_url": "https://api.met.no/weatherapi/locationforecast/2.0/compact",
        "refresh_policy": "PT1H",
        "freshness_window_seconds": 10800,
        "capabilities": ["forecast", "point_geometry", "timeseries", "global"],
        "configuration": {"required_parameters": ["lat", "lon"]},
    },
    {
        "id": "nasa.gibs-wmts",
        "source_id": "nasa-earthdata",
        "name": "NASA GIBS WMTS Layer Registry",
        "domain": "earth_observation",
        "description": "NASA GIBS capabilities catalog normalized into discoverable map-layer records.",
        "adapter": "nasa_gibs_wmts_v1",
        "base_url": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 172800,
        "max_response_bytes": 12582912,
        "capabilities": ["wmts", "map_layers", "satellite_imagery", "global"],
        "configuration": {"projection": "EPSG:4326"},
    },
    {
        "id": "usgs.earthquakes",
        "source_id": "usgs",
        "name": "USGS Earthquake Summary Feed",
        "domain": "hazards",
        "description": "Near-real-time earthquake events from official USGS GeoJSON summary feeds.",
        "adapter": "usgs_earthquakes_geojson_v1",
        "base_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary",
        "refresh_policy": "PT5M",
        "freshness_window_seconds": 3600,
        "capabilities": ["events", "geojson", "near_real_time", "global"],
        "configuration": {"default_feed": "all_hour", "allowed_feeds": ["all_hour", "all_day", "2.5_day", "4.5_week", "significant_month"]},
    },
    {
        "id": "world-bank.indicators",
        "source_id": "world-bank",
        "name": "World Bank Development Indicators",
        "domain": "economics",
        "description": "Country and aggregate indicator observations through the World Bank V2 API.",
        "adapter": "world_bank_indicators_v2",
        "base_url": "https://api.worldbank.org/v2",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "countries", "development", "sustainability"],
        "configuration": {"required_parameters": ["indicator"], "default_country": "all"},
    },
    {
        "id": "fred.series-observations",
        "source_id": "fred",
        "name": "FRED Series Observations",
        "domain": "economics",
        "description": "Economic series observations using a free registered FRED API key.",
        "adapter": "fred_series_observations_v1",
        "base_url": "https://api.stlouisfed.org/fred/series/observations",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "vintages", "economic_releases"],
        "configuration": {"required_parameters": ["series_id"], "credential_env": "SC_CORE_FRED_API_KEY", "public_records": False},
    },
    {
        "id": "un.sdg-catalog",
        "source_id": "un-statistics",
        "name": "UN SDG Goal and Series Catalog",
        "domain": "sustainability",
        "description": "Official SDG goal and indicator-series catalog discovery.",
        "adapter": "un_sdg_catalog_v1",
        "base_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/v1/sdg",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 604800,
        "capabilities": ["sdg_goals", "indicator_series", "official_metadata", "global"],
        "configuration": {"default_resource": "goals", "allowed_resources": ["goals", "series"]},
    },

    {
        "id": "un.digital-library", "source_id": "un-digital-library", "name": "UN Digital Library Official Document Search", "domain": "international_law",
        "description": "Searches official UN document metadata and classifies resolution and document authority.", "adapter": "un_digital_library_search_v1",
        "base_url": "https://digitallibrary.un.org/search", "refresh_policy": "manual", "freshness_window_seconds": 604800,
        "capabilities": ["official_documents", "resolutions", "voting_records", "speeches", "legal_authority", "search"],
        "configuration": {"required_parameters": ["query"], "default_fields": "recid,title,document_symbol,publication_date,creation_date,language,subjects,collections,urls"},
    },
    {
        "id": "un.sdg-metadata", "source_id": "un-statistics", "name": "UN SDG Metadata Reports", "domain": "sustainability",
        "description": "Retrieves official SDG methodology reports by series and reference area.", "adapter": "un_sdg_metadata_v1",
        "base_url": "https://unstats.un.org/SDGMetadataAPI/api/Metadata", "refresh_policy": "P7D", "freshness_window_seconds": 2592000,
        "capabilities": ["sdg_metadata", "methodology", "sdmx_report"], "configuration": {"required_parameters": ["series"]},
    },
    {
        "id": "ocha.reliefweb-reports", "source_id": "ocha-reliefweb", "name": "OCHA ReliefWeb Reports", "domain": "humanitarian",
        "description": "Curated humanitarian reports with countries, sources, themes, and publication dates.", "adapter": "reliefweb_reports_v2",
        "base_url": "https://api.reliefweb.int/v2/reports", "refresh_policy": "PT1H", "freshness_window_seconds": 86400,
        "capabilities": ["reports", "disasters", "countries", "humanitarian_events", "search"],
        "configuration": {"credential_env": "SC_CORE_RELIEFWEB_APPNAME", "public_records": True},
    },
    {
        "id": "ocha.hdx-hapi", "source_id": "ocha-hdx-hapi", "name": "HDX Humanitarian Indicators", "domain": "humanitarian",
        "description": "Standardized humanitarian indicators through HDX HAPI v2.", "adapter": "hdx_hapi_v2",
        "base_url": "https://hapi.humdata.org/api/v2", "refresh_policy": "P1D", "freshness_window_seconds": 604800,
        "capabilities": ["humanitarian_indicators", "population", "needs", "funding", "food_security", "operational_presence"],
        "configuration": {"default_resource": "affected-people/refugees-persons-of-concern", "allowed_resources": ["affected-people/refugees-persons-of-concern", "affected-people/idps", "affected-people/humanitarian-needs", "coordination-context/operational-presence", "coordination-context/funding", "food-security-nutrition-poverty/food-security", "geography-infrastructure/baseline-population", "climate/hazards-rainfall"]},
    },
    {
        "id": "un.population-data", "source_id": "un-population", "name": "UN Population Data Portal", "domain": "demographics",
        "description": "Official demographic indicator observations by location and year range.", "adapter": "un_population_data_v1",
        "base_url": "https://population.un.org/dataportalapi/api/v1", "refresh_policy": "P30D", "freshness_window_seconds": 31536000,
        "capabilities": ["population", "fertility", "mortality", "migration", "projections", "timeseries"],
        "configuration": {"required_parameters": ["indicators", "locations", "start_year", "end_year"], "optional_bearer_env": "SC_CORE_UN_POPULATION_BEARER_TOKEN"},
    },
    {
        "id": "un.comtrade", "source_id": "un-comtrade", "name": "UN Comtrade Public Trade Data", "domain": "economics",
        "description": "Public-preview international trade flows by reporter, period, partner, commodity, and flow.", "adapter": "un_comtrade_public_v1",
        "base_url": "https://comtradeapi.un.org/public/v1/preview/C/A/HS", "refresh_policy": "P1D", "freshness_window_seconds": 2592000,
        "capabilities": ["trade", "imports", "exports", "commodities", "partners", "timeseries"],
        "configuration": {"required_parameters": ["reporter_code", "period"], "public_preview_limit": 500},
    },
    {
        "id": "unhcr.population", "source_id": "unhcr", "name": "UNHCR Refugee Population Statistics", "domain": "humanitarian",
        "description": "Official annual statistics on displaced and stateless populations.", "adapter": "unhcr_population_v1",
        "base_url": "https://api.unhcr.org/population/v1/population/", "refresh_policy": "P30D", "freshness_window_seconds": 31536000,
        "capabilities": ["refugees", "asylum_seekers", "idps", "statelessness", "solutions", "demographics"],
        "configuration": {"optional_parameters": ["coo", "coa", "year_from", "year_to"]},
    },
    {
        "id": "ohchr.uhri-recommendations", "source_id": "ohchr", "name": "OHCHR Universal Human Rights Index", "domain": "international_law",
        "description": "Country-specific human-rights recommendations with themes, mechanisms, and SDG links.", "adapter": "ohchr_uhri_v1",
        "base_url": "https://uhri.ohchr.org/", "refresh_policy": "P1D", "freshness_window_seconds": 604800,
        "capabilities": ["human_rights_recommendations", "treaty_bodies", "special_procedures", "upr", "sdg_links"],
        "configuration": {"credential_env": "SC_CORE_UHRI_API_URL", "registration_url": "https://uhri.ohchr.org/en/our-data-api"},
    },

]
