from __future__ import annotations

from datetime import datetime, timezone

REVIEWED_AT = datetime(2026, 7, 14, tzinfo=timezone.utc)

DEFAULT_LIVE_DATA_SOURCES: list[dict] = [
    {
        "id": "met-norway",
        "name": "MET Norway Weather API",
        "organization": "Norwegian Meteorological Institute",
        "description": "Official global forecast data and related meteorological services.",
        "homepage_url": "https://api.met.no/",
        "documentation_url": "https://api.met.no/weatherapi/locationforecast/2.0/documentation",
        "license_name": "Creative Commons attribution terms; provider terms apply",
        "license_url": "https://api.met.no/doc/TermsOfService",
        "attribution": "Norwegian Meteorological Institute",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_with_attribution",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed_with_identifying_user_agent",
        "rate_limit_summary": "Cache responses and identify the application with a contact-bearing User-Agent.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "Norway"},
    },
    {
        "id": "nasa-earthdata",
        "name": "NASA Earthdata",
        "organization": "National Aeronautics and Space Administration",
        "description": "Official Earth science metadata, imagery, and visualization services.",
        "homepage_url": "https://www.earthdata.nasa.gov/",
        "documentation_url": "https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api",
        "license_name": "United States Government public data; dataset-specific terms apply",
        "license_url": "https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-information-policy",
        "attribution": "NASA EOSDIS",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_gibs",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use standards-compliant access and cache capabilities metadata.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "usgs",
        "name": "USGS Earthquake Hazards Program",
        "organization": "United States Geological Survey",
        "description": "Official earthquake catalog, feeds, and geospatial event data.",
        "homepage_url": "https://earthquake.usgs.gov/",
        "documentation_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
        "license_name": "United States Government public data; source attribution requested",
        "license_url": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
        "attribution": "U.S. Geological Survey",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed",
        "redistribution_status": "allowed_with_attribution",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use summary feeds for frequent polling and catalog queries for bounded searches.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "world-bank",
        "name": "World Bank Indicators API",
        "organization": "World Bank Group",
        "description": "Official development indicators, country metadata, and time-series observations.",
        "homepage_url": "https://data.worldbank.org/",
        "documentation_url": "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information",
        "license_name": "World Bank data terms; dataset-specific terms apply",
        "license_url": "https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets",
        "attribution": "World Bank",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none",
        "commercial_use_status": "allowed_subject_to_dataset_terms",
        "redistribution_status": "allowed_subject_to_dataset_terms",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use pagination and local caching for repeated indicator requests.",
        "review_status": "APPROVED_WITH_ATTRIBUTION",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },
    {
        "id": "fred",
        "name": "Federal Reserve Economic Data",
        "organization": "Federal Reserve Bank of St. Louis",
        "description": "Official and aggregated economic time series with release and vintage metadata.",
        "homepage_url": "https://fred.stlouisfed.org/",
        "documentation_url": "https://fred.stlouisfed.org/docs/api/fred/",
        "license_name": "FRED terms and underlying series-provider terms",
        "license_url": "https://fred.stlouisfed.org/legal/",
        "attribution": "Federal Reserve Bank of St. Louis and the named series source",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "free_registration",
        "commercial_use_status": "series_specific_review_required",
        "redistribution_status": "series_specific_review_required",
        "automated_access_status": "allowed_with_api_key",
        "rate_limit_summary": "A free registered API key is required; preserve each series source and notes.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "jurisdiction": "United States"},
    },
    {
        "id": "un-statistics",
        "name": "United Nations Statistics Division SDG API",
        "organization": "United Nations Statistics Division",
        "description": "Official Sustainable Development Goal catalog, series, observations, and metadata.",
        "homepage_url": "https://unstats.un.org/sdgs/",
        "documentation_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/swagger/index.html",
        "license_name": "United Nations data terms; dataset and agency terms apply",
        "license_url": "https://www.un.org/en/about-us/terms-of-use",
        "attribution": "United Nations Statistics Division and reporting custodian agencies",
        "access_cost": "free",
        "credit_card_required": False,
        "api_key_requirement": "none_for_catalog",
        "commercial_use_status": "review_required_by_dataset",
        "redistribution_status": "review_required_by_dataset",
        "automated_access_status": "allowed",
        "rate_limit_summary": "Use bounded catalog and extraction requests and preserve agency metadata.",
        "review_status": "APPROVED_METADATA_ONLY",
        "last_reviewed_at": REVIEWED_AT,
        "metadata": {"official": True, "scope": "global"},
    },
]

DEFAULT_LIVE_DATA_CONNECTORS: list[dict] = [
    {
        "id": "met-no.locationforecast",
        "source_id": "met-norway",
        "name": "MET Norway Global Location Forecast",
        "domain": "weather",
        "description": "Coordinate-based nine-day weather forecast normalized into metric observations.",
        "adapter": "met_locationforecast_v2",
        "base_url": "https://api.met.no/weatherapi/locationforecast/2.0/compact",
        "refresh_policy": "PT1H",
        "freshness_window_seconds": 10800,
        "capabilities": ["forecast", "point_geometry", "timeseries", "global"],
        "configuration": {"required_parameters": ["lat", "lon"]},
    },
    {
        "id": "nasa.gibs-wmts",
        "source_id": "nasa-earthdata",
        "name": "NASA GIBS WMTS Layer Registry",
        "domain": "earth_observation",
        "description": "NASA GIBS capabilities catalog normalized into discoverable map-layer records.",
        "adapter": "nasa_gibs_wmts_v1",
        "base_url": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 172800,
        "max_response_bytes": 12582912,
        "capabilities": ["wmts", "map_layers", "satellite_imagery", "global"],
        "configuration": {"projection": "EPSG:4326"},
    },
    {
        "id": "usgs.earthquakes",
        "source_id": "usgs",
        "name": "USGS Earthquake Summary Feed",
        "domain": "hazards",
        "description": "Near-real-time earthquake events from official USGS GeoJSON summary feeds.",
        "adapter": "usgs_earthquakes_geojson_v1",
        "base_url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary",
        "refresh_policy": "PT5M",
        "freshness_window_seconds": 3600,
        "capabilities": ["events", "geojson", "near_real_time", "global"],
        "configuration": {"default_feed": "all_hour", "allowed_feeds": ["all_hour", "all_day", "2.5_day", "4.5_week", "significant_month"]},
    },
    {
        "id": "world-bank.indicators",
        "source_id": "world-bank",
        "name": "World Bank Development Indicators",
        "domain": "economics",
        "description": "Country and aggregate indicator observations through the World Bank V2 API.",
        "adapter": "world_bank_indicators_v2",
        "base_url": "https://api.worldbank.org/v2",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "countries", "development", "sustainability"],
        "configuration": {"required_parameters": ["indicator"], "default_country": "all"},
    },
    {
        "id": "fred.series-observations",
        "source_id": "fred",
        "name": "FRED Series Observations",
        "domain": "economics",
        "description": "Economic series observations using a free registered FRED API key.",
        "adapter": "fred_series_observations_v1",
        "base_url": "https://api.stlouisfed.org/fred/series/observations",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 2592000,
        "capabilities": ["indicators", "timeseries", "vintages", "economic_releases"],
        "configuration": {"required_parameters": ["series_id"], "credential_env": "SC_CORE_FRED_API_KEY", "public_records": False},
    },
    {
        "id": "un.sdg-catalog",
        "source_id": "un-statistics",
        "name": "UN SDG Goal and Series Catalog",
        "domain": "sustainability",
        "description": "Official SDG goal and indicator-series catalog discovery.",
        "adapter": "un_sdg_catalog_v1",
        "base_url": "https://unstats.un.org/sdgs/UNSDGAPIV5/v1/sdg",
        "refresh_policy": "P1D",
        "freshness_window_seconds": 604800,
        "capabilities": ["sdg_goals", "indicator_series", "official_metadata", "global"],
        "configuration": {"default_resource": "goals", "allowed_resources": ["goals", "series"]},
    },
]
