from __future__ import annotations

DEFAULT_WORKFLOW_DEFINITIONS = [
    {
        "id": "research-to-signature-dossier",
        "name": "Research to Signature Dossier",
        "description": "End-to-end route from problem framing through research, live source intelligence, analysis, evidence review, trust evaluation, dossier approval, signature, and publication.",
        "version": "1.0",
        "public": True,
        "active": True,
        "sort_order": 10,
        "metadata": {"release": "2.5.0", "workflow_family": "decision-support"},
        "stages": [
            {"key":"frame","name":"Frame the decision","product":"decision-studio","action":"frame","required":True},
            {"key":"research","name":"Build the research route","product":"research-librarian","action":"research-route","required":True},
            {"key":"sources","name":"Collect source and indicator intelligence","product":"site-intelligence","action":"source-intelligence","required":True},
            {"key":"analysis","name":"Run models and calculations","product":"workbench","action":"analysis","required":True},
            {"key":"evidence","name":"Review claims and evidence","product":"platform-core","action":"evidence-review","required":True},
            {"key":"trust","name":"Run trust evaluations","product":"trust-center","action":"evaluation-suite","required":True},
            {"key":"assemble","name":"Assemble the signature dossier","product":"platform-core","action":"dossier-assembly","required":True},
            {"key":"approve","name":"Approve and sign the dossier","product":"platform-core","action":"approval-signature","required":True},
            {"key":"publish","name":"Publish or deliver the final package","product":"wordpress","action":"publication","required":True},
        ],
    },
    {
        "id": "evidence-assurance-dossier",
        "name": "Evidence Assurance Dossier",
        "description": "Review claims, sources, calculations, provenance, findings, limitations, and attestations before issuing an assurance dossier.",
        "version": "1.0",
        "public": True,
        "active": True,
        "sort_order": 20,
        "metadata": {"release": "2.5.0", "workflow_family": "assurance"},
        "stages": [
            {"key":"scope","name":"Define assurance scope","product":"decision-studio","action":"scope","required":True},
            {"key":"collect","name":"Collect claims and source snapshots","product":"research-librarian","action":"evidence-collection","required":True},
            {"key":"validate","name":"Validate calculations and provenance","product":"workbench","action":"validation","required":True},
            {"key":"evaluate","name":"Run evaluation framework","product":"trust-center","action":"evaluation-suite","required":True},
            {"key":"remediate","name":"Resolve or accept findings","product":"platform-core","action":"remediation","required":True},
            {"key":"dossier","name":"Assemble and sign assurance dossier","product":"platform-core","action":"dossier-signature","required":True},
        ],
    },
    {
        "id": "dashboard-publication-dossier",
        "name": "Dashboard Publication Dossier",
        "description": "Prepare a public dashboard with source health, indicator lineage, visualization validation, accessibility review, and a signed publication record.",
        "version": "1.0",
        "public": True,
        "active": True,
        "sort_order": 30,
        "metadata": {"release": "2.5.0", "workflow_family": "public-dashboard"},
        "stages": [
            {"key":"sources","name":"Verify connectors and source freshness","product":"site-intelligence","action":"source-health","required":True},
            {"key":"indicators","name":"Validate indicator lineage","product":"site-intelligence","action":"indicator-lineage","required":True},
            {"key":"visuals","name":"Validate dashboard calculations and visual outputs","product":"workbench","action":"visual-validation","required":True},
            {"key":"accessibility","name":"Review accessibility","product":"trust-center","action":"accessibility-evaluation","required":True},
            {"key":"dossier","name":"Assemble publication dossier","product":"platform-core","action":"dossier-assembly","required":True},
            {"key":"publish","name":"Approve and publish dashboard","product":"wordpress","action":"publication","required":True},
        ],
    },
]
