#!/usr/bin/env python3
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
def check(label, cond):
    if not cond: raise SystemExit(f"{label}=FAIL")
    print(f"{label}=PASS")
config=(ROOT/'backend/app/config.py').read_text()
main=(ROOT/'backend/app/main.py').read_text()
service=(ROOT/'backend/app/services/contextual_causal_language_mechanism.py').read_text()
router=(ROOT/'backend/app/routers/contextual_causal_language_mechanism.py').read_text()
readme=(ROOT/'README.md').read_text()
wp=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/sustainable-catalyst-platform-core.php').read_text()
wpread=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/readme.txt').read_text()
v414v=(ROOT/'scripts/validate_v4140_release.py').read_text()
m=re.search(r'version: str = \"(\d+)\.(\d+)\.(\d+)\"',config)
check('PLATFORM_CORE_V4150_BACKEND_VERSION',m is not None and tuple(map(int,m.groups())) >= (4,15,0))
check('PLATFORM_CORE_V4150_ROUTE_MOUNT','contextual_causal_language_mechanism.router' in main and 'contextual_causal_language_mechanism.public_router' in main)
check('PLATFORM_CORE_V4150_SERVICE_RELEASE','CORE_RELEASE = "4.15.0"' in service)
check('PLATFORM_CORE_V4150_CONTRACT','sc.core.contextual-causal-language-mechanism-intelligence.v1' in service)
check('PLATFORM_CORE_V4150_API_SURFACE','/v1/causal-context' in router and '/public/v1/causal-context' in router)
check('PLATFORM_CORE_V4150_CAUSAL_SIGNAL_FOUNDATION',all(x in service for x in ['CausalLanguageSignal','CausalLanguageKind','CausalRelationKind']))
check('PLATFORM_CORE_V4150_MECHANISM_FOUNDATION',all(x in service for x in ['MechanismHypothesis','MechanismState','mechanism_is_hypothesis_not_validated_pathway']))
check('PLATFORM_CORE_V4150_INTERVENTION_FOUNDATION',all(x in service for x in ['InterventionContext','CausalEvidenceClass','sufficient_for_causal_identification']))
check('PLATFORM_CORE_V4150_COUNTERFACTUAL_FOUNDATION',all(x in service for x in ['CounterfactualContext','counterfactual_question_is_not_effect_estimate']))
check('PLATFORM_CORE_V4150_ASSESSMENT_FOUNDATION',all(x in service for x in ['CausalAssessment','establishes_causal_truth']))
check('PLATFORM_CORE_V4150_PROVENANCE_SNAPSHOT',all(x in service for x in ['CausalProvenanceRecord','CausalSemanticSnapshot','deterministic_causal_context_fingerprint_sha256']))
check('PLATFORM_CORE_V4150_EPISTEMIC_BOUNDARY',all(x in service for x in ['causal_language_is_distinct_from_causal_identification','temporal_precedence_is_not_causality','association_is_not_causality','mechanism_plausibility_is_not_mechanism_validation','counterfactual_language_is_not_counterfactual_estimate']))
check('PLATFORM_CORE_V4150_MUTATION_BOUNDARY',all(x in service for x in ['automatic_causal_graph_mutation_authorized','evidence_graph_mutation_authorized','knowledge_graph_mutation_authorized','identity_graph_mutation_authorized']))
check('PLATFORM_CORE_V4150_README','v4.15.0 — Contextual Causal Language & Mechanism Intelligence' in readme)
mw=re.search(r'Version: (\d+)\.(\d+)\.(\d+)',wp); mc=re.search(r"SCPC_VERSION', '(\d+)\.(\d+)\.(\d+)",wp)
check('PLATFORM_CORE_V4150_WORDPRESS_VERSION',mw is not None and mc is not None and tuple(map(int,mw.groups())) >= (4,15,0) and tuple(map(int,mc.groups())) >= (4,15,0))
ms=re.search(r'Stable tag: (\d+)\.(\d+)\.(\d+)',wpread)
check('PLATFORM_CORE_V4150_WORDPRESS_STABLE_TAG',ms is not None and tuple(map(int,ms.groups())) >= (4,15,0))
check('PLATFORM_CORE_V4150_SCHEMA',(ROOT/'schemas/sc-core-contextual-causal-language-mechanism-intelligence-v1.schema.json').exists())
check('PLATFORM_CORE_V4150_TEST_COVERAGE',(ROOT/'backend/tests/test_contextual_causal_language_mechanism_v4150.py').exists())
check('PLATFORM_CORE_V4150_V414_FORWARD_COMPATIBILITY','>= (4,14,0)' in v414v or '>= (4, 14, 0)' in v414v)
check('PLATFORM_CORE_V4150_NO_DB_MIGRATION','database_migration: Literal["none"]' in service)
print('PLATFORM_CORE_V4150_VALIDATION=PASS')
