#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def check(label,cond):
    if not cond: raise SystemExit(f"{label}=FAIL")
    print(f"{label}=PASS")
config=(ROOT/'backend/app/config.py').read_text()
main=(ROOT/'backend/app/main.py').read_text()
service=(ROOT/'backend/app/services/narrative_framing_perspective.py').read_text()
router=(ROOT/'backend/app/routers/narrative_framing_perspective.py').read_text()
readme=(ROOT/'README.md').read_text()
wp=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/sustainable-catalyst-platform-core.php').read_text()
wpread=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/readme.txt').read_text()
v415v=(ROOT/'scripts/validate_v4150_release.py').read_text()
import re
_version_match=re.search(r'version: str = \"(\d+)\.(\d+)\.(\d+)\"', config)
_app_version=tuple(map(int,_version_match.groups())) if _version_match else (0,0,0)
check('PLATFORM_CORE_V4160_BACKEND_VERSION',_app_version >= (4,16,0))
check('PLATFORM_CORE_V4160_ROUTE_MOUNT','narrative_framing_perspective.router' in main and 'narrative_framing_perspective.public_router' in main)
check('PLATFORM_CORE_V4160_SERVICE_RELEASE','CORE_RELEASE = "4.16.0"' in service)
check('PLATFORM_CORE_V4160_CONTRACT','sc.core.narrative-framing-perspective-intelligence.v1' in service)
check('PLATFORM_CORE_V4160_API_SURFACE','/v1/narrative-framing' in router and '/public/v1/narrative-framing' in router)
check('PLATFORM_CORE_V4160_PERSPECTIVE_FOUNDATION',all(x in service for x in ['SourcePerspective','perspective_is_observed_source_position_not_private_motive']))
check('PLATFORM_CORE_V4160_SIGNAL_FOUNDATION',all(x in service for x in ['FramingSignal','FramingDimension','EmphasisState','signal_is_not_bias_verdict']))
check('PLATFORM_CORE_V4160_FRAME_FOUNDATION',all(x in service for x in ['NarrativeFrame','NarrativeFrameKind','frame_is_interpretive_description_not_truth_verdict']))
check('PLATFORM_CORE_V4160_COMPARISON_FOUNDATION',all(x in service for x in ['PerspectiveComparison','PerspectiveRelationship','comparison_establishes_bias']))
check('PLATFORM_CORE_V4160_ASSESSMENT_FOUNDATION',all(x in service for x in ['NarrativeFramingAssessment','establishes_motive']))
check('PLATFORM_CORE_V4160_PROVENANCE_SNAPSHOT',all(x in service for x in ['NarrativeFramingProvenanceRecord','NarrativeFramingSnapshot','deterministic_framing_context_fingerprint_sha256']))
check('PLATFORM_CORE_V4160_EPISTEMIC_BOUNDARY',all(x in service for x in ['framing_is_descriptive_not_truth_adjudication','emphasis_is_not_manipulation','omission_is_not_deception','perspective_is_not_private_motive','framing_analysis_is_not_ideology_classification']))
check('PLATFORM_CORE_V4160_MUTATION_BOUNDARY',all(x in service for x in ['automatic_context_graph_mutation_authorized','automatic_evidence_graph_mutation_authorized','automatic_knowledge_graph_mutation_authorized','automatic_identity_graph_mutation_authorized']))
check('PLATFORM_CORE_V4160_README','v4.16.0 — Narrative, Framing & Perspective Intelligence' in readme)
_wp_version_match=re.search(r'Version: (\d+)\.(\d+)\.(\d+)', wp)
_wp_version=tuple(map(int,_wp_version_match.groups())) if _wp_version_match else (0,0,0)
check('PLATFORM_CORE_V4160_WORDPRESS_VERSION',_wp_version >= (4,16,0))
_wp_tag_match=re.search(r'Stable tag: (\d+)\.(\d+)\.(\d+)', wpread)
_wp_tag=tuple(map(int,_wp_tag_match.groups())) if _wp_tag_match else (0,0,0)
check('PLATFORM_CORE_V4160_WORDPRESS_STABLE_TAG',_wp_tag >= (4,16,0))
check('PLATFORM_CORE_V4160_SCHEMA',(ROOT/'schemas/sc-core-narrative-framing-perspective-intelligence-v1.schema.json').exists())
check('PLATFORM_CORE_V4160_TEST_COVERAGE',(ROOT/'backend/tests/test_narrative_framing_perspective_v4160.py').exists())
check('PLATFORM_CORE_V4160_V415_FORWARD_COMPATIBILITY','>= (4,15,0)' in v415v or '>= (4, 15, 0)' in v415v)
check('PLATFORM_CORE_V4160_NO_DB_MIGRATION','database_migration: Literal["none"]' in service)
print('PLATFORM_CORE_V4160_VALIDATION=PASS')
