#!/usr/bin/env python3
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
def check(label,cond):
    if not cond: raise SystemExit(f"{label}=FAIL")
    print(f"{label}=PASS")
config=(ROOT/'backend/app/config.py').read_text()
main=(ROOT/'backend/app/main.py').read_text()
service=(ROOT/'backend/app/services/contextual_hypothesis_competing_explanations.py').read_text()
router=(ROOT/'backend/app/routers/contextual_hypothesis_competing_explanations.py').read_text()
readme=(ROOT/'README.md').read_text()
wp=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/sustainable-catalyst-platform-core.php').read_text()
wpread=(ROOT/'wordpress-plugin/sustainable-catalyst-platform-core/readme.txt').read_text()
v417v=(ROOT/'scripts/validate_v4170_release.py').read_text()
_version_match=re.search(r'version: str = "(\d+)\.(\d+)\.(\d+)"', config)
_app_version=tuple(map(int,_version_match.groups())) if _version_match else (0,0,0)
check('PLATFORM_CORE_V4180_BACKEND_VERSION',_app_version >= (4,18,0))
check('PLATFORM_CORE_V4180_ROUTE_MOUNT','contextual_hypothesis_competing_explanations.router' in main and 'contextual_hypothesis_competing_explanations.public_router' in main)
check('PLATFORM_CORE_V4180_SERVICE_RELEASE','CORE_RELEASE = "4.18.0"' in service)
check('PLATFORM_CORE_V4180_CONTRACT','sc.core.contextual-hypothesis-competing-explanation-objects.v1' in service)
check('PLATFORM_CORE_V4180_API_SURFACE','/v1/context-hypotheses' in router and '/public/v1/context-hypotheses' in router)
check('PLATFORM_CORE_V4180_HYPOTHESIS_FOUNDATION',all(x in service for x in ['ContextualHypothesis','HypothesisKind','hypothesis_is_explanation_candidate_not_truth','fit_score_is_not_probability_or_truth']))
check('PLATFORM_CORE_V4180_EVIDENCE_POSITION_FOUNDATION',all(x in service for x in ['HypothesisEvidencePosition','EvidencePositionKind','evidence_position_is_not_truth_update']))
check('PLATFORM_CORE_V4180_COMPARISON_FOUNDATION',all(x in service for x in ['CompetingExplanationComparison','ExplanationRelation','comparison_does_not_select_winner']))
check('PLATFORM_CORE_V4180_SET_FOUNDATION',all(x in service for x in ['CompetingExplanationSet','set_establishes_winner','rejected_hypothesis_refs']))
check('PLATFORM_CORE_V4180_PROVENANCE_SNAPSHOT',all(x in service for x in ['ContextualHypothesisProvenanceRecord','ContextualHypothesisSnapshot','deterministic_hypothesis_context_fingerprint_sha256']))
check('PLATFORM_CORE_V4180_EPISTEMIC_BOUNDARY',all(x in service for x in ['hypotheses_are_explanatory_objects_not_truth_claims','explanatory_fit_score_establishes_truth','explanatory_fit_score_is_probability','support_count_establishes_truth','challenge_count_establishes_falsity','retained_hypothesis_is_selected_winner']))
check('PLATFORM_CORE_V4180_MUTATION_BOUNDARY',all(x in service for x in ['automatic_hypothesis_promotion_authorized','automatic_context_graph_mutation_authorized','automatic_evidence_graph_mutation_authorized','automatic_knowledge_graph_mutation_authorized','automatic_identity_graph_mutation_authorized']))
check('PLATFORM_CORE_V4180_README','v4.18.0 — Contextual Hypothesis & Competing Explanation Objects' in readme)
_wp_version_match=re.search(r'Version: (\d+)\.(\d+)\.(\d+)', wp)
_wp_version=tuple(map(int,_wp_version_match.groups())) if _wp_version_match else (0,0,0)
check('PLATFORM_CORE_V4180_WORDPRESS_VERSION',_wp_version >= (4,18,0))
_wp_tag_match=re.search(r'Stable tag: (\d+)\.(\d+)\.(\d+)', wpread)
_wp_tag=tuple(map(int,_wp_tag_match.groups())) if _wp_tag_match else (0,0,0)
check('PLATFORM_CORE_V4180_WORDPRESS_STABLE_TAG',_wp_tag >= (4,18,0))
check('PLATFORM_CORE_V4180_SCHEMA',(ROOT/'schemas/sc-core-contextual-hypothesis-competing-explanation-objects-v1.schema.json').exists())
check('PLATFORM_CORE_V4180_TEST_COVERAGE',(ROOT/'backend/tests/test_contextual_hypothesis_competing_explanations_v4180.py').exists())
check('PLATFORM_CORE_V4180_V417_FORWARD_COMPATIBILITY','_app_version >= (4,17,0)' in v417v and '_wp_version >= (4,17,0)' in v417v and '_wp_tag >= (4,17,0)' in v417v)
check('PLATFORM_CORE_V4180_NO_DB_MIGRATION','database_migration: Literal["none"]' in service)
print('PLATFORM_CORE_V4180_VALIDATION=PASS')
